[#_3_1]
=== Description as a graphic: The Unified Modeling Language UML

A diagram is well suited to supply oneself or others with an overview to a model. That is why in information technology already since the mid 1970's graphic notation has been used to visualize models. Though for a long time it seemed impossible to agree on a uniform representation so that dozens of notations were in use at the same time. Finally at the beginning of the 1990's three methods (Booch, OMT and OOSE) prevailed. In 1995/96 their creators, the so-called «three amigos», agreed on one single modeling language the _Unified Modeling Language (UML)_. Since 1997 UML as a standard is being administered and maintained by an industrial syndicate, the _Object Management Group_.

UML is flexible and versatile. Whoever is familiar with its notation may grasp at first sight models from the most varied application ranges. By the way this language is not only suitable for the modeling of data (by means of the class diagrams presented in this paper). It also comprises elements for other aspects of a system for example the division in components or scenarios for its utilization.

An important factor for the success of UML is its adaptability: For many applications this language provides a sufficient infrastructure, nevertheless at any given moment it is possible to adapt this language to your proper needs by means of clearly defined equally standardized mechanisms of extension.

A visual language such as UML has its many advantages, however it is not the ideal tool for all applications. As soon as it is a matter of determining details of a large and complex model a drawing may become badly arranged and confusing. Besides, a graphic representation is rather unpractical e.g. where the arranging of computer systems is concerned. Hence in some cases a text form would be more suited: The models are formulated as a text in a standard language and thus become comprehensible for humans and computers likewise. Naturally enough the picture may still serve as a rough overview. At present suggestions for a purely textual notation of UML is being discussed, but until now no corresponding standard has been decided on.

[#_3_2]
