[#_3_2]
=== Description as text: INTERLIS

In Switzerland it has been known for a long time that a model-based concept has its considerable advantages. Within the scope of cadastral surveying the textual modeling language INTERLIS was developed in 1991. Towards the end of the 1990's INTERLIS 2 was drawn up, which expanded and modernized the previous version. Have a dozen of specialists out of research, administration and industry ensured that this language would meet all demands of practical operation. Furthermore great importance was attached to the support to some particularities that are a result of the application:

* INTERLIS permits a precise and in the highest degree detailed description of data models. Hence an INTERLIS-model may directly become a component of an advertisement text, a contract or a decree and it is also possible to configure a program package based on an INTERLIS-model.
* INTERLIS does not only comprise a language for the modeling of data but also a procedure which permits the derivation of a transfer format for the exchange of the modeled data from a model. This is of major importance because the collection of geographical data is extremely costly and hence very valuable. Furthermore their life span comprises decades, in other words it is distinctly longer than that of information technology systems, which generally become antiquated within a few years. Such expensively collected data can only be protected if they are maintained in a form independent from a concrete program.
* Even though it is also possible to use INTERLIS in applications without any geographical reference whatsoever it is extremely well suited to space-related data. Already at the very core of the language geometry is supported. Moreover measures have been taken that permit the automatic examination of data supplied with regard to quality and plausibility.
* INTERLIS-data models have a clear structure: A model is divided into topics, which then comprise object classes. The description of an object class features object-properties as well as consistency and plausibility restraints. On both levels, i.e. models as well as topics, it is possible to declare commonly employed constructs (e.g. units, value domains, auxiliary structures, etc.).
* The federalist structure of Switzerland with its 26 cantons and semi-cantons, which are further divided into administrative units, makes high demands on a modeling language. INTERLIS 2 allows all parties concerned to use one, in its essence common data model, which then is expanded and refined according to regional needs. A smooth exchange of data is guaranteed even if locally different models are being used. Moreover INTERLIS permits that models and data can be drawn up in different languages. Thus each part of the country may use its own official language.

INTERLIS and UML complement one another: UML-diagrams are easy to draw and ideal for providing a rough overview. By using INTERLIS details may be captured in a precise and nevertheless easy to comprehend form, furthermore special support is offered where requirements of the federalist geodata-practice are concerned. There are tools that permit automatic conversion of UML-class diagrams into INTERLIS-descriptions. The reverse is also possible: the representation of an INTERLIS-model in UML-notation may take place automatically.

[#_3_3]
