[#_5_2]
=== Refine what has been inherited

In general one hundred signs may be appropriate for the name of one particular alpine transport. After all at a time it had been considered to run a «Children and Family tow-rope Mount Ilis area». However at the very last minute it was decided to use «pony lift» instead, to the great relief of the local tourist organization.

But a tramway line with one hundred signs? Five signs should definitely be enough.

[#listing-05_02-01]
.link:#listing-05_02-01[Listing 05.02-01]
[source]
----
CLASS Railway =
  Name: TEXT*100;
END Railway;

CLASS AlpineTransport EXTENDS Railway =
  PosBottomStation: NationalCoord;
  PosTopStation: NationalCoord;
END AlpineTransport;

CLASS TramwayLine EXTENDS Railway =
  Name (EXTENDED): TEXT*5;
END TramwayLine;
----

Figure 27: Five signs are sufficient for the name of a Tramway Line: The type of the property «Name» is refined by the sub class (specified). On the right hand side the same is stated in the notation of INTERLIS.

The specified, refined information must be compatible with the one inherited. For instance the maximum length for a tramway line may not exceed the length of the common railway.

[NOTE]
====
Sub classes can *refine* inherited properties. However the specified information may not contradict the one inherited: they must be *compatible* with the definition of the super class.

_Otherwise a sub class might feature objects that are not part of the set of all objects of the super class._
====

[#_5_3]
