[#_6_3]
=== Is there such a thing as light blue ski runs? – Structured enumeration

[#_6_3_1]
==== Ordinary enumeration and its laws of inheritance

In order to achieve a rough distinction between the difficulty degrees of ski runs, three colors had been chosen: blue, red, black. These and only these difficulty degrees should prevail. Furthermore they all relate to an order. Blue depicts a simple ski run, a red run is more difficult than a blue one, and a black one is the most demanding. The following definition would describe this circumstance:

[source]
----
CLASS SkiRun =
  DifficultyDegree: (blue, red, black: FINAL) ORDERED;
END SkiRun;
----

If the FINAL-indication were to be missing, then this enumeration could still be added onto in an extension. For instance in the case of different kinds of alpine transport this might make sense:

[source]
----
!! Model of the National Tourist Office
CLASS AlpineTransport =
  Kind: (CogRail, Funicular, AerialCableCar,
        SkiLift, ChairLift, Gondola);
END AlpineTransport;

!! Model Ilis Valley
CLASS MITAlpineTransport EXTENDS AlpineTransport =
  Kind (EXTENDED): (SnowBus);
END MITAlpineTransport;
----

In the extended class the element snow bus is added to the enumeration – the latest of all novelties – at the end of the existing enumeration. But what will the National Tourist Office make of that? For them «Snow bus» is still unheard of.

[NOTE]
Each (horizontal) extension can be complemented with further value as long as it is not expressively excluded by *FINAL*. If somebody is only interested in these values in general according to the basic class, then all these values will be translated into the value *OTHER*.

For the basic class the value snow bus - and other possible values - are only recognizable as OTHER. However if FINAL is indicated, then the value OTHER no longer can occur. If an enumeration is defined as circular (*CIRCULAR*) then such extensions are impossible because circular means that the highest value is followed by the lowest and hence it would be impossible to know which of them is the highest.

[source]
----
WindDirection: (N, NE, E, SE, S, SW, W, NW) CIRCULAR;
----

[#_6_3_2]
==== Sub-enumeration

Thu s it had been decided not to model the different kinds of alpine transport with an entire landscape of classes. But all the railway enthusiasts were not quite satisfied: who knows if at some stage the cog system of the cog rail would not be of interest after all...

For each value of an enumeration a sub-enumeration can be defined. This may happen directly within the basic definition or only in an extension.

[source]
----
CLASS MITAlpineTransport EXTENDS AlpineTransport
  Kind (EXTENDED): (CogRail (Riggenbach, Abt, vonRoll));
END MITAlpineTransport;

WeekDay: (WorkingDay (Monday, Tuesday, Wednesday,
                      Thursday, Friday, Saturday),
         Sunday);
----

If such an enumeration is defined within an extension, then it is simply of no importance from the base's point of view. So as far as the National Tourist Office is concerned a Riggenbach-cog rail would still be a cog rail.

Even sub-enumeration can be complemented with further values, as long as value has not been declared FINAL. The individual values of a sub-enumeration again can be specified by sub enumeration, which would result in entire enumeration trees.

[#_6_4]
