[#_6_1]
=== Sovereigns and pennies – Numeric data types

[#_6_1_1]
==== Value domain

A simple ticket for a single ride with the funicular up to Mount Ilis costs 10 Ahland sovereigns, a yearly sport pass is worth 635 sovereigns. So how should the price of a ticket be modeled?

Whoever is used to dealing with programming language would think immediately of whole number («Integer») or floating point number («Real»). With many programming languages and data base it is possible to determine the memory space a number will take up, hence ensue size and precision of the numbers that can be stored («short integer», «long integer», «double precision», etc.). Thus one would consider the domain within which the value would approximately be situated and choose storage accordingly.

When modeling at conceptual level most likely one would not want to be bothered with storage. However it is possible to indicate the highest and lowest value admissible and to determine at the same time the number of digits and exponents.

Since prices lie between 10 and 635 sovereigns we could then write:

[#listing-06_01-01]
.link:#listing-06_01-01[Listing 06.01-01]
[source]
----
Price: 10 .. 635;
----

However this would also decide that the price can never be less than 10 sovereigns or more than 635 sovereigns, which of course is very undesirable. As a lower limit 0 seems plausible. But the upper limit? It is unlikely to be more than 10'000 sovereigns. So 10'000? Wherever because of a particular application a precise limit cannot be determined, in any case it would not make sense to select the value just so that shorter storage (e.g__. short integer__ with value between –32768 and 32767) would not be sufficient.

Of course it is also important to consider the number of decimals necessary. If prices may feature pennies then the limit would have to be set with to decimals. With an attribute which for instance represents an investment budget you are likely to deal in millions, when dealing with dimensions two digits will be sufficient. However these may refer to a thousand, a million or even a billion.

[#listing-06_01-02]
.link:#listing-06_01-02[Listing 06.01-02]
[source]
----
Price: 0.00 .. 9999.99;
Budget: 0.00E6 .. 999.99E6;
GrossNationalProduct: 0.0E0 .. 9.9E20;
----

The number of decimals describes the precision: «4.3 Million» (4.3E6 = 4.3 · 106) is not as precise an indication as «4300000».

[#_6_1_2]
==== Units

Now do we deal with sovereigns, francs, Euro or dollars? Units are – not only where money is concerned – of paramount importance. That is why we recommend indicating the unit not only as a comment or part of the attribute name but actually as constituent of the type:

[#listing-06_01-03]
.link:#listing-06_01-03[Listing 06.01-03]
[source]
----
UNIT
  Sovereign EXTENDS MONEY;

CLASS TicketType =
  Price: 0 .. 9999 [Sovereign];
END TicketType;
----

Sovereigns (or Swiss francs, Euro, dollars, etc.) are defined as units and can then be used when defining a numeric type. However most common units (amongst others also CHF, EUR, USD) actually need not be defined but are available via the specific units model (units.ili, cf. paragraph <<_3_3>>).

[WARNING]
In the interest of clarity we recommend indicating units at any time. The INTERLIS-units-model comprises, besides numerous physical units, such units for common currencies and for number, percent and per mille.

[#_6_1_3]
==== Inheriting numeric types

Since the Mount Ilis Alpine Transports will never issue tickets that cost over a thousand sovereigns, one might come up with the idea of defining this in its own class:

[#listing-06_01-04]
.link:#listing-06_01-04[Listing 06.01-04]
[source]
----
CLASS TicketType (EXTENDED) =
  Price (EXTENDED): 0 .. 1000 [sovereigns];
END TicketType;
----

In this application this concrete example does not make much sense really. But in real life there certainly are cases where limiting the inherited value domain is a sensible thing to do.

Nevertheless those in charge in Ilis Valley cannot suit themselves where the value domains of the national models are concerned. The principle applies that each Illis Valley value also has to be admissible in the basic model of the National Tourist Office. Otherwise we could not ensure a smooth transfer of data from Ilis Valley to the National Tourist Office.

Thus an indication of price 0 .. 1000 is an admissible restriction of the value domain provided nationally of 0 .. 9999. If the value domain in Ilis Valley were to be extended – for instance with an indication of 0 .. 15000 – then all ticket types ranging between 10000 and 15000 were incorrect from the National Tourist Office's point of view. Hence such a definition is inadmissible.

The people in charge in Ilis Valley also insist on the possibility of issuing tickets with prices that not necessarily have to be an entire sovereign. One would like to write the following definition:

[#listing-06_01-05]
.link:#listing-06_01-05[Listing 06.01-05]
[source]
----
CLASS TicketType (EXTENDED) =
  Price (EXTENDED): 0.00 .. 1000.00 [Sovereign];
END TicketType;
----

Then again, would this be compatible with the basic model? Yes, because according to the Illis Valley model (e.g. 7.35) with a mathematical rounding each value can be mapped onto a correct value of the national model (e.g. 7).

The definition would be inadmissible if it were to comprise values that once rounded violate the basic model. For instance the maximum value of 9999.99 once rounded would become 10000 – which would be more than the 9999 predefined by the National Tourist Office. However Ilis Valley could define a value ranging from 0.00 .. 9999.49 without contradicting the basic model, because after rounding 9999.49 would become again 9999.

It is also inadmissible to renounce precision in the specified model. For instance if the national tourism model were to provide a domain of 0.00 .. 1000.00 Illis Valley could not indicate 0 .. 1000 in their specification.

And furthermore: Units of the extension must always be in accordance with those of the basic model!

[#_6_1_4]
==== Limits as yet unknown

Can the National Tourist Office determine what price is admissible for a ticket? If the limits are still entirely unknown, then – within the scope of abstract attributes – their notation can be omitted. Nevertheless it is possible to already determine a unit.

[#listing-06_01-06]
.link:#listing-06_01-06[Listing 06.01-06]
[source]
----
Price (ABSTRACT): NUMERIC [Ahland.Sovereign];
----

Maybe even the unit is still uncertain. It would only be known that e deal with e.g. a currency.

[#listing-06_01-07]
.link:#listing-06_01-07[Listing 06.01-07]
[source]
----
Price (ABSTRACT): NUMERIC [MONEY];
----

Thus at least the character of the unit would be settled. Therefore in an extension only such units could be defined as would figure as concretes of the abstract unit MONEY (for further information concerning abstract properties also see paragraph <<_5_4>>).

[#listing-06_01-08]
.link:#listing-06_01-08[Listing 06.01-08]
[source]
----
Price (EXTENDED): 0 .. 10000 [CHF]; !! admissible
Price (EXTENDED): 0 .. 2000 [USD]; !! admissible
Price (EXTENDED): 0 .. 1000 [m]; !! inadmissible, because meter
                                  !! specifies LENGTH and not MONEY.
----

[#_6_2]
