[#_6_5]
=== Calm – Optional and mandatory attributes

Current operational data also include weather data such as temperature, direction and force of wind. When it is calm it makes no sense to indicate the direction of the wind. All other information should always be displayed.

[NOTE]
The fact that an attribute can be *undefined*, respectively that it always has to be defined, forms part of the model.

[WARNING]
Undefined is not simply 0 or some other slightly exceptional value. It is an independent value, which clearly reflects the fact of being undefined.

For instance in INTERLIS 2 we would write:

[#listing-06_05-01]
.link:#listing-06_05-01[Listing 06.05-01]
[source]
----
CLASS Weather =
  Temperature: MANDATORY –50 .. 50 [oC];
  WindDirection: (N, NE, E, SE, S, SW, W, NW) CIRCULAR;
  WindSpeed: MANDATORY 0 .. 200 [kmh];
END Weather
----

Hence both temperature and wind speed are compulsory (MANDATORY). Since the wind direction is not compulsory, it is optional. Thus the concrete value may be undefined. In extensions it is admissible to turn optional attributes into mandatory attributes. However mandatory attributes may never be turned into optional attributes, because in accordance with the basic class the value «undefined» is not permitted.

[#_6_6]
