[#_6_10]
=== What way does the wind blow? - Structures

[#_6_10_1]
==== Multiple properties

Just before Ilis Rock travelers on the chair lift from Ilis Dale pull their hats tightly over their ears: At this spot the wind tends to rip and whistle. When it comes to wind, it is not only speed that is decisive, but also direction. If, in a class description, both these properties simply appear along with other attributes, not enough emphasis will be put on this relevant fact.

[#listing-06_10-01]
.link:#listing-06_10-01[Listing 06.10-01]
[source]
----
CLASS Weather =
  Temperature: MANDATORY -50 .. 50 [oC];
  WindDirection: MANDATORY (N, NE, E, SE, S, SW, W, NW) CIRCULAR;
  WindSpeed: MANDATORY 0 .. 200 [kmh];
END Weather;
----

In situations where a specific fact cannot be described by only one value, it makes sense to define a structure combining both characteristics (wind direction, wind speed).

[#listing-06_10-02]
.link:#listing-06_10-02[Listing 06.10-02]
[source]
----
STRUCTURE IndicationOfWind =
  WindDirection: MANDATORY (N, NE, E, SE, S, SW, W, NW) CIRCULAR;
  WindSpeed: MANDATORY 0 .. 200 [kmh];
END IndicationOfWind;
----

Other concepts related to structure are: data type, structured data type, ....

This particular structure can be used whenever we deal with comments on wind.

[#listing-06_10-03]
.link:#listing-06_10-03[Listing 06.10-03]
[source]
----
CLASS Weather =
  Temperature: MANDATORY -50 .. 50 [oC];
  Wind: IndicationOfWind;
END Weather;

CLASS WindMeter =
  Position: MANDATORY NationalCoord;
  Wind: IndicationOfWind;
END WindMeter;
----

[#_6_10_2]
==== Several elements of structure

The wind-meter stationed at Ilis Rock is more special yet: It does not only display the current value, but also six values recorded previously. While this of course does not warm your ears, it is still quite astonishing to note how swiftly conditions can change.

[#listing-06_10-04]
.link:#listing-06_10-04[Listing 06.10-04]
[source]
----
CLASS WindMeter =
  Position: MANDATORY NationalCoord;
  Wind: LIST {6} OF IndicationOfWind;
END WindMeter;
----

Therefore the attribute wind comprises six elements (six values each with speed and direction). LIST Of states that their order is relevant (e.g. the most recent value comes first). If the order were not relevant, this would be indicated by BAG OF. As with relationships there is a possibility to indicate the minimum and maximum number of elements.

[#_6_10_3]
==== Structures and classes

From a formal point of view structures and (object) classes are quite similar, however with regard to their content there are considerable differences. A class (railway company, wind-meter) describes how objects are formed, organized. A structure describes more complex characteristics such as indication of wind. Hence a structure serves the same goal as a domain, it describes the organization of an attribute. Sometimes a structure only becomes necessary, if a characteristic must be described more in detail; for simple descriptions indicating a domain is sufficient (cf. paragraph <<_6_12>>).

Instances of classes are objects in their own right (Mount Ilis Alpine Transports, wind-meter at Ilis Rock). The instances of structures are structure elements (wind with a speed of 180km/h, blowing from a north-easterly direction). The value of a structure attribute can comprise exactly one structure element or a set of structure elements (BAG OF, LIST OF).

[NOTE]
While formally a *structure* closely resembles an object class, with regard to its contents it resembles a domain. However its corresponding items, its *structure elements,* do not have an identity of their own, they merely are values of attributes of an object. 

Whereas relationships may exist between objects (cf. paragraph <<_6_13>>), the same is not possible between values (of domains or structures). However it is possible to compare similar values of distinct objects (and distinct classes) and thus establish a kind of relationship (cf. paragraph <<_6_17>>). For instance one might compare the price of a hiker's pass with the price of a steak one intends to order at the restaurant on top of Mount Ilis. Nevertheless there is no relationship between the hiker's pass and the steak.

In some cases it is necessary to refer to another object in order to describe a particular characteristic (cf. paragraph <<_6_11_3>>). Yet it will never be possible to refer to a value or a structure element, as they have no identity.

[#_6_10_4]
==== Lines are special structures

The attribute course of a ski run (cf. paragraph <<_6_9_1>>) is defined as AhlandLine, which in turn is defined as POLYLINE. A POLYLINE may be understood as a set of segments of a line (cf. paragraph <<_6_9_2>>). Thus the definition as POLYLINE is nothing but a shortened notation for an ordered set of structures, the structures elements corresponding to a certain structure definition:

[#listing-06_10-05]
.link:#listing-06_10-05[Listing 06.10-05]
[source]
----
STRUCTURE AhlandSegment (ABSTRACT) =
  SegmentEndPoint: MANDATORY Ahland.NationalCoord;
END AhlandSegment;

STRUCTURE AhlandStartSegment EXTENDS AhlandSegment (FINAL) =
END AhlandStartSegment;

STRUCTURE AhlandStraightSegment EXTENDS AhlandSegment (FINAL) =
END AhlandStraightSegment;

STRUCTURE AhlandArcSegment EXTENDS AhlandSegment (FINAL) =
  ArcPoint: MANDATORY Ahland.NationalCoord;
  Radius: Length;
END AhlandArcSegment;

CLASS SkiRun =
  Course: LIST {2..*} OF AhlandSegment;
END SkiRun;
----

[#_6_11]
