[#_6_14]
=== Unique MountIlisAlpineTransports – Consistency constraints

[#_6_14_1]
==== General remarks

We recall that the Mount Ilis Alpine Transports want to report information on current conditions for each of their alpine transports, amongst others the weather at the top station:

[source]
----
CLASS InformationOnCondition =
  Temperature: MANDATORY –50 .. 50 [oC];
  WindDirection: (N, NE, E, SE, S, SW, W, NW) CIRCULAR;
  WindSpeed: MANDATORY LengthOfTimeInMinutes;
  Captured MANDATORY MomentInTimeCET;
END InformationOnCondition;
----

With this definition even a report stating an undefined wind direction and a wind speed of 60 km/h would be acceptable. This is not our goal. An undefined wind direction should mean calm. But then of course wind speed would be 0. And vice versa with a wind speed greater than zero the wind direction should always be defined.

[NOTE]
Situations where a certain connection has to exist between different attributes of an object or even between different objects are described by means of *consistency constraints*.

As a rule consistency constraints are described by a formula whose interpretation will tell whether the condition is fulfilled or not. Thanks to such a logical expression we will come to terms with a lull:

[source]
----
CLASS InformationOnCondition =
  Temperature: MANDATORY –50 .. 50 [oC];
  WindDirection: (N, NE, E, SE, S, SW, W, NW) CIRCULAR;
  WindSpeed: MANDATORY 0 .. 200 [kmh];
  WaitingTime: LengthOfTimeInMinutes;
  Captured: MANDATORY MomentInTimeCET;
  MANDATORY CONSTRAINT
    DEFINED (WindDirection) == (WindSpeed > 0);
END InformationOnCondition;
----

Precisely when the wind direction is defined, then the wind speed must be greater than zero. If no wind direction is defined, then speed has to be zero. Hence «Definiteness» of the wind direction must equal (==) «Positiveness» of the wind speed.

Very often consistency constraints could be omitted if only the model were structured differently. If we wrap up all indications regarding wind in a structure, and then state that this structure, there is no need for a consistency constraint. With no wind the structure element is missing. If it is blowing then forcibly there must be both wind direction and wind speed.

[source]
----
STRUCTURE IndicationOfWind =
  WindDirection: MANDATORY (N, NE, E, SE, S, SW, W, NW) CIRCULAR;
  WindSpeed: MANDATORY 0 .. 200 [kmh];
END IndicationOfWind;

CLASS InformationOnConditions =
  Temperature: MANDATORY –50 .. 50 [oC];
  Wind: IndicationOfWind;
  WaitingTime: LengthOfTimeInMinutes;
  Captured: MANDATORY MomentInTimeCET;
END InformationOnConditions;
----

[WARNING]
With consistency constraints – especially if they are complicated – we always suspect that the optimal model has not yet been found. On the other hand there is no sense in making an extra effort to render a basically simple model complicated only to avoid a consistency constraint.

[#_6_14_2]
==== Plausibility constraints

Any employee of the Mount Ilis Alpine Transports makes good money, but still the managing director's salary is something different.

In general consistency constraints apply to all objects of the corresponding class. In INTERLIS 2 they are called MANDATORY CONSTRAINT. Occasionally we speak of «hard» conditions, because they always have to be fulfilled. But there are also conditions that on principle, but not always are complied with.

With attributes such as monthly salaries and body-height the generally admissible scope must be relatively. However the values of most objects will lie below a considerably lower limit, but exceptions may occur, for instance the salary of the managing director.

[source]
----
ASSOCIATION Employment =
  ...
  MonthlySalary: MANDATORY 0 .. 20000 [Sovereigns];
  ...
  CONSTRAINT >= 95%
    MonthlySalary < 10000;
END Employment;
----

We estimate that in a minimum of (>=) 95% of all cases the monthly salary is below 10000 sovereigns. If a model comprises such «soft » condition, there is the possibility to check data with regard to plausibility and to examine it statistically during input.

[#_6_14_3]
==== Uniqueness constraints

How can we identify persons that either work for the company or are participants? It might seem obvious to use names and first names but this would be quite unsuitable:

[source]
----
CLASS Person =
  Name: TEXT*50;
  FirstName: TEXT*20;
  UNIQUE Name, FirstName;
END Person;
----

Consequently it would become inadmissible to list to persons with the same combination of name and first name. Hence the new engine driver John Smith could only start his job after his namesake the accountant has been sacked.

What would be a better uniqueness constraint? Why even bother with uniqueness constraints?

[NOTE]
A *uniqueness constraint* does not serve the identification of an object within the program package. It describes instead what combination of attributes must be technically unique.

[NOTE]
Program-internally and during data exchange an object is marked by a technical *object identifier*. It is of no importance whatsoever for the application.

Hence we do not need a uniqueness constraint for every object class just to be able to identify the object. It is sufficient if the data object that corresponds to the actual person can be found during data input. For this purpose we can use attributes, relationships etc. without a combination having to be unequivocal.

However if it is a system external identification we are aiming at, which e.g. would be comprehensible to human beings, we need an attribute or a combination of attributes whose values are unequivocal with regard to all objects. Very often artificial attributes are created (insurance number, client numbers, article number, etc.)

[WARNING]
Wherever possible avoid artificial identifiers. If nevertheless they are necessary, make sure they do not contain items of other attributes in redundant form.

For the Mount Ilis Alpine Transports a simple solution has been found for this problem: A number for every employee has been introduced. Anybody new at the Mount Ilis Alpine Transports will be assigned a number that has not been bestowed on before.

[source]
----
CLASS Person =
  Name: TEXT*50;
  FirstName: TEXT*20;
  Employee'sNumber: 1 .. 9999;
  UNIQUE Employee'sNumber;
END Person;
----

The whole thing would become more tricky if the class that describes these persons were not defined by the Mount Ilis Alpine Transports but by the national association instead. The number of any person within the scope of the association would have to be unequivocal – even if they were gathered decentrally. If there happened to be two numbers (e.g. one at the Mount Ilis Alpine Transports, another at the Blue Mountains Alpine Transports__),__ then the constraint would be violated.

[NOTE]
Uniqueness constraints always apply to all objects that correspond to the class for which this constraint has been drafted – even if they only correspond indirectly (in the form of an extension of the class.

One railway company may possess several names. However per language there should only be one single designation, hence the Mount Ilis Alpine Transports may not have a second German name. Then again this constraint only apllies locally, in other words per company. After all the Blue Mountains Alpine Transports also have a German name. With regard to all companies there definitely is more than one name in the same language. The language of these designations must be unequivocal for one specific railway company.

[NOTE]
If an object features sub structures, uniqueness – as opposed to the actual objects – as a rule should not apply «globally» to the elements of all sub-structures. In most cases it only refers «locally» to the sub-structure elements of one single object.

[source]
----
STRUCTURE Designation =
  Name: TEXT*100;
  Language: TEXT*2;
END Designation;

STRUCTURE DesignationOfRailway EXTENDS Designation =
  Abbreviation: TEXT*10;
END DesignationOfRailway;

CLASS RailwayCompany =
  Names: BAG {1..*} OF DesignationOfRailway;
  UNIQUE
    (LOCAL) Names : Language;
END RailwayCompany;
----

But how can we avoid collisions between the abbreviations of various railway companies? Both the Blue Mountain Alpine Transport as well as the Black Mountain Alpine Transports would in the first place like to be known as BMT. In INTERLIS 2 consistency constraints cannot only be formulated for object classes respectively local structure elements but also for views (cf. paragraph <<_6_17>>). By means of a certain view we can make structure elements into basically independent objects. Then in turn we can formulate uniqueness constraints for them.

[#_6_14_4]
==== Existence constraints

As opposed to cog rails and funiculars, the course of the tracks of aerial cable cars, gondolas, ski lifts etc. is not arbitrary but linked to their bottom and top station as well as their pylons.

We wish to express this context. However the lines of INTERLIS 2 connect vertices, which primarily are coordinates, and are devoid of any reference to model objects such as pylons for instance. The connection between the course of the track and other objects may be formulated as a consistency constraint.

Using the following definition every point within the course of the track has to rely either on the position of a pylon (Pylon:Position), the position of the bottom station of an alpine transport (AlpineTransport:PosBottomStation) or (OR) the position of the top station of an alpine transport (AlpineTransport:PosTopStation).

[source]
----
CLASS GroundIndependentTransport EXTENDS AlpineTransport =
  EXISTENCE CONSTRAINT
    TrackCourse REQUIRED IN
      Pylon:Position
      OR
      AlpineTransport:PosBottomStation
      OR
      AlpineTransport:PosTopStation;
END GroundIndependentTransport;
----

Such existence constraints cannot only be formulated in connection with lines but also with ordinary attributes. In conceptual terms they can always be considered a weak form of a relationship.

[#_6_14_5]
==== Inheritance of consistency constraints

Already with the alpine transport itself a consistency constraint had been formulated: The course of the track has to start at the bottom station and end at the top station. In other words, the first point of the course of a track (Tracks -> Segments[FIRST] -> SegmentEndPoint) must coincide with the position of the bottom station and (AND) the last point of the course of a track (Tracks -> Segments[LAST] -> SegmentEndPoint) must coincide with the position of the top station.

Paragraph <<_7_3>> explains the structure of polylines. It also deals with the attribute SegmentEndPoint, which stands for the end point of a line segment.

[source]
----
CLASS AlpineTransport =
  PosBottomStation: Ahland.NationalCoord3;
  PosTopStation: Ahland.NationalCoord3;
  TrackCourse: Ahland.LineNormal;
  MANDATORY CONSTRAINT
    Tracks -> Segments[FIRST] -> SegmentEndPoint == PARENT == PosBottomStation
    AND
    Tracks -> Segments[LAST] -> SegmentEndPoint == PARENT == PosTopStation;
END AlpineTransport;
----

What does such a definition mean when it comes to possible extensions of this class?

[NOTE]
Class extensions cannot rule out consistency constraints. Extensions can only define additional constraints.

[#_6_15]
