[#_7_1]
=== What are standard conform systems? – System neutrality

Various program packages, e.g. NatTourSys used by the national association, but also LiftSys employed by the Mount Ilis Alpine Transports, have implemented the models defined by INTERLIS 2. They are capable of establishing and reading corresponding files. Consequently are they INTERLIS-systems? To put the question more generally: When does a system comply with a certain standard?

A description at conceptual level does not aim at dictating the way a computer system implements the idea portrayed. As a rule systems have their own possibilities to realize concrete applications. Ideally the internal data model can be derived directly from the descriptions but this is no prerequisite. It is quite conceivable that a system cannot directly process data. In order to be compatible it is good enough for a system to be able to process data directly or indirectly according to a (e.g. by means of supplementary conversion programs. Whenever possible a norm for data modeling should not dictate the concrete manner in which the systems convert the application. Creativity is what we are after, there should be room for free enterprise. There must be system independence of the standard; otherwise desirable system changes may fail because of the incompatibility of data.

Then again a system need not possess the entire range of capacities that are conceivable in connection with a description. For instance WebSys can do nothing but collect INTERLIS 2-data. More extreme still are those systems that send condition reports from the individual alpine transports to the central office. In a very rudimentary way report data are inserted into prepared files that are structured according to the rules of the standard.

If an application makes very special requirements, we cannot expect them to be covered by a generally applicable norm. In such cases support is a matter of contract with the system manufacturers. However exercising restraint is recommended, because at the same time you will lose part of your system-independence and limit the circle of possible system providers.

Named below two examples depict how system dependent aspects can be standardized without in a major way influencing the systems internally.

[#_7_2]
