[#_8_1]
=== Out of mind, out of sight – Full transfer

Let's recall: In Ilis Valley they had carefully considered which data was needed for their projected application and had documented their ideas with a data model. In the course of their discussions it had become apparent that working with both graphic representation and detailed textual description was helpful.

After many a lengthy discussion those in charge in Ilis Valley had gotten there: The standard program package «LiftSys» was acquired and arranged according to the Ilis Valley data model. Even though things did not go quite as smooothly as promised by the LiftSys-sales representative, these initial difficulties were not hard to overcome. And finally the data of all transport lines, railway companies, ski runs etc. in Ilis Valley had been collected.

Proudly the IT-expert demonstrated how with one single mouse click the entire Ilis Valley data could be exported into an INTERLIS 2-file. Some spectators were not easily enthused and critical questions were asked: All these meetings for one miserable file? Had that really been necessary?

All objection was quickly squashed once the accountant explained just how many sovereigns the data exchange had cost them per year up until now. Every time data had had to be transferred to the national association there had been trouble. How many hours of work had been time wasted!

From now on it would be possible to send one file with all the Ilis Valley data to the national association and they would be able to process them without any problems.

[NOTE]
The simplest type of transfer is the *full transfer*, whereby all data are transferred as a whole.

The fact that a transfer goes smoothly even if not all the parties concerned use the same data model is due to inheritance as explained in paragraph <<_5_5>>.

[#_8_2]
