[#_8_2]
=== Brackets as pointed as Mount Ilis – Transfer rules based on XML

What was actually in this file? It was opened with a normal text editor.

.The Ilis Valley pony lift as part of the full transfer for Ilis Valley data. The INTERLIS-standard defines the precision with which such a transfer file has to be structured for a certain data model.
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
...
<BASKET BID="xAHTOUMIT01234567" TOPICS="IlisTour.AlpineTransports">
  <IlisTour.MITAlpineTransports.MITAlpineTransport
   TID="xAHTOUMIT04231336">
    <Names>
      <NatTour.Designation>
        <Name>Pony lift Ilis Ville</Name> <1>
        <Language>en</Language>
      </NatTour.Designation>
    </Names>
    ...
    <PosTopStation>
      <P>
        <C1>8020.60</C1>
        <C2>13188.62</C2>
        <C3>1789.04</C3>
      </P>
    </PosTopStation>
    <TravelTime>
      <Ahland.LengthOfTimeInMinutes>
        <Duration>3</Duration>
      </Ahland.LengthOfTimeInMinutes>
    </TravelTime>
    <Kind>SkiLift</Kind>
    ...
    <PictureTopStation>
      http://www.ilishornbahnen.com/webcam?bahn=pony4
    </PictureTopStation>
    ...
  </IlisTour.MITAlpineTransports.MITAlpineTransport>
</BASKET>
...
----

Quite a few pointed brackets, at the very beginning something about XML (that had been mentioned somewhere earlier along the way!), even though with question marks... Aha, something simple for a change:

<1> The pony lift Ilis Ville

Depending on the data model a transfer file has a different structure. But of course it is not completely arbitrary: The INTERLIS-standard states precise rules as to how the corresponding XML format is to be derived from a specific data model.

Slightly complicated, this whole thing – but luckily LiftSys could be used and all these brackets never had to be entered by hand. At least even without a special program it was evident that the travel time on the pony lift is 3 minutes.

The IT-expert explained that even in forty years' time they would still be able to work with these data. Even supposing that by then the manufacturers of the original programs had gone bankrupt, fifteen new program versions had had to be installed and all the hardware had been exchanged. This statement appeared to be quite plausible because even without any documentation and on paper it was possible (though rather awkward) to understand these data.

But what about this funny text «TID="xAHTOUMIT04231336"»? It designates the pony lift within the transfer file. The value is only of importance for the transfer: This object identifier appears wherever in the transfer file there is a reference to the pony lift. During installation of LiftSys it had been possible to indicate that all identifiers should begin with xAHTOUMIT, exactly as had been demanded by the National Tourist Office in their letter.

Object identifiers begin with a country code in accordance with ISO 3166 (ch for Switzerland, fr for France, etc.) and six other symbols uniquely assigned by the appropriate, central authority. The eight remaining symbols are automatically assigned by the computer system.

For explanations about object identifiers see appendix E of the INTERLIS-reference manual.

[#_8_3]
