[#_8_3]
=== Once and over and over again – Incremental update

As much as seventeen minutes on the pony lift? Those poor kids will be frozen stiff before they will even have attempted their first stem turn! This line will hardly survive its first season, how could anybody still be interested in its data forty years from now?

Finally it turned out that the pony lift was not tremendously oversized – somebody had simply made a typing-mistake while entering data: Instead of seventeen minutes the ride would only take all of one minute.

Of course it did not take long to change that figure in LiftSys. But did this mean all the data had to be sent once more to the national association?

[NOTE]
Thanks to *incremental update* it is no longer necessary to send all data after a modification, it is enough to transfer the modifications themselves. This saves transferring data but the real advantage lies in the fact that it provides at the same time a documentation of the exact nature of modifications.

By means of the LiftSys-program an update for the national association had been generated. In contrast with the full transfer this update did not comprise all data of the entire Ilis Valley but only data of modified objects. Consequently it turned out to be much smaller and easier to handle.

Yet it does not always make sense to do an incremental update. For instance the National Tourist Office does not offer itself the internet-service where tourists can find information about the prices of tickets at the various lines, instead they have delegated this task to one of their sister companies. Periodically they are sent a complete copy of all data in INTERLIS 2-format. These data are loaded by a server-program, which answers any concrete question. An incremental update would increase requirements on the server-program without any visible profit.

[#_8_4]
