[#_9_4]
=== Not seeing the wood for the trees – Degree of specification

Beyond question we will not model real life as if the individual atoms that form real-life items were our data objects. That would be far too awkward. Nor should a building be composed of its individual bricks and tiles. But when do we speak of individual trees, and when of a forest without listing each tree as a data object?

Of course this depends on what we want to achieve with the system. What is the use in finding the best possible model if it cannot be realized? Is the model comprehensible? Is it possible to define a dialog for both data-collection and update, which the people intended for the job, can handle?

Especially in this respect a simple model whose object classes are not overly tangled up, may have a positive impact.

The more complicated a model, the more important an intuitively understandable user surface becomes. In such situations it is dangerous to extend a basic model in such a way that not only attributes are added but new relationships are defined as well. There is a considerable risk that the user dialog designed for the basic model loses its elegance and comprehensibility.

Once again we should keep in mind: «As simple as possible, as complex as necessary». But as we all know the adequate realization of this maxim is not quite as easy.

[#_9_5]
