[#_9_2]
=== Mount Ilis seen from different angles – Original data and views

If we only go by our immediate needs when modeling, we run the risk of collecting data in an unsuitable way. For instance it is not suitable to use the age of a person as an attribute since it will change continuously. It is preferable to define the date of birth as an attribute and then to derive the age by means of a view from the date of birth and the current date (cf. paragraph <<_6_17_2>>).

If the structure of a data model corresponds to the actual facts rather than to a certain point of view, we are more flexible with regard to concrete uses that can be derived from the original data. These data will contain Mount Ilis rather than the view from Ilis Ville or Ilis Bath. These and various other perspectives can be derived as views from our data.

Sometimes the derivation of desirable views from «ideally» modeled data can be quite demanding. Above all views containing, die formation laws with geometrical calculations are not always easy to realize. The decision when to swerve from virtue and to adjust a data model to a view is not always an easy one and in general depends on various criteria. Even if you decide on a model that does not describe the actual data but a view on them, it is worthwhile considering which would be the «nice» model. It will be easier to return to this model at a given time and thus to overcome the disadvantages of a view-oriented model.

The biggest disadvantage of a view-oriented model will become apparent in the collecting and above all in the up dating of data. For instance if for every house entrance we state the street name, the house number, the zip-code and town as a direct attribute, there is a certain risk that mistakes occur e.g. due to different spelling. Furthermore this in a major way increases the costs of collecting data. Worse still when it gets to incremental update, for instance if the new settlement Ilis Mill will be introduced as a village with its own zip code and the lower part of Ilis Ville will be classed with this new village. Do all house entrances have to be muted It would be much better if this new village with its validity domain could be introduced and then the validity domain of Ilis Ville was adjusted accordingly.

Thanks to good models one modified fact in real life will lead to exactly one modification in our data. All the rest can be derived by means of views.

[#_9_3]
