[#_10_3]
=== III. System independent description of the data structure

In order to transfer electronic mappings of real life – in other words data – from one system to another, we have to have a definite notion of what these data look like, how they are structured. The hard nut to be cracked being: These structure descriptions also have to be independent of any concrete system. They have to be conceived in such a way that they can be equally interpreted and understood by application experts as well as technical specialists of all authorities concerned. Ideally this description would even have a structure that not only human beings but also computer programs can deal with. What we need is a standardized Esperanto of data description.

In everyday speech Esperanto has remained without the slightest significance. Something livelier, possible also more convenient prevailed. Matters are slightly different where technology is concerned. Who does not aspire to system independence will be ruled by systems. And systems are relatively short-lived. Hence the realization that in spite of many de facto-standards _Unified Modeling Language_ (UML), a graphic language within the scope of data modeling has spread worldwide.

In intensive discussions a model of real life has been sketched. To start with we had to make clear what the relevant items were, how they had to be named in a comprehensible way, how they inter-acted and what other characteristics they possessed. The protocol of these discussions always recorded new findings in the UML-graphic language and added comments and explanations. Since it became apparent that the pictures were loaded with too many details and in some cases did not have the required precision and additional description-tool was used in the form of INTERLIS: Similarly to programming language it permits the precise description of data structure.

An important characteristic supported by both UML and INTERLIS 2 is the possibility to also use data descriptions made at other locations. Thus it had been possible to profit from definitions of cadastral surveying for instance in the case of building addresses. Data descriptions of the National Tourist Office were not only used but complemented according to local needs, too.

[#_10_4]
