[#_10_2]
=== II. Items, mappings and the ravages of time

To call in one more expert had definitely been a good move, even if the first talks had turned out to be quite surprising. Few technical catchwords were mentioned and mostly swept aside; instead a thorough analysis of the entire matter was conducted.

First conclusion: Facts are not what is in a computer or even what it spits out in the way of pictures, tables or other presentations, facts are what exists and happens in real life.

What is in the computer can be compared to a wooden model or a sandpit. The pictures we might take of them from different angles and with different lighting correspond to the screen or to prints. And one thing that is also obvious with wooden models or a sandpit: to copy real life for the first time is a giant task. Just what it takes to build a simplified version of all the houses, streets, railway companies that exist in reality! Even more complicated than the first input is the update of it all. Hardly completed, and already there are first alterations to be made in order to keep the representation up to date. And time is not kind to sand or plaster structures. Computers are comparatively easy to handle! Of course we have to make updates on changes of the reality, but at least the remaining information does not become antiquated.

Really? No, definitely not as fast as in a sandpit. But after a few years we would like to buy a new, more powerful computer, and a little later still the software employed will no longer be the best on the market. Assuming one would like to use new programs, how would one transfer the electronic replica of real life from the old onto the new system? How would we shift the sand from the old pit to the new without it running through our fingers and all our work having to be recommenced?

[#_10_3]
