[#_11]
== Register

References to comprehensive explanations in <<_4>> are set in _italics._

A

Abstract _35_, 46

Address 29, 112

on the internet _See_ URI

Aggregation 93

with relationships _35_, 76

with views 93

Angle 61

Arc segment 63, 99

Area _See_ Tessellation

Association _35_, 76

Attribute 13

mandatory 55

optional 55

with relationships 77

Auxiliary point 99

B

Basic class _See_ Inheritance

Basket 88, 103

Bézier curve 99

Booch 27

C

Cadastral surveying 29, 112

Cardinality 12

Character codes 24

Character coding 24

Class diagram 11

Clothoide 99

Coding 24

Column 13

Compatibility 47

Compiler 30, 95, 105

Composition _39_, 76

Consistency constraints _38_, 83

and inheritance 87

with segment points 87

Contract 98

Coordinate system 57

Coordinates _32_, _34_, 56

in space _32_, 60

to establish connections 82

Currency 50, 98

D

Data exchange _See_ Transfer

Data model 11, 111

description as a graphic 27

multilingual 95

standardized 28, 89

Data set 11

Data type 13, _32_, 56

geometrical 63

numeric _36_, 50

structured 73

Description _See_ Data model

Description of data 27

Dimension 49

Direction 61

E

Ellipsoid 57

Ellipsoid height 60

Enclave 65

Entity 11

Enumeration _35_, 51

and inheritance _37_, 51

circular _39_, 54

final 54

ordered _40_, 53

structured 54

Example 11

Existence constraints 86

Extension _See_ Inheritance

F

Federalism 28, 47, 113

Field 13

Floating point number 49

Formation law See View

Full transfer 16

Function _37_, 97

G

General case _See_ Inheritance

Geoid 60

GML 29

Graphic 25

Gravity height 60

H

Height 60

I

Identification

allocation 103

at the transfer 102, 104

with attributes 85

Incremental update 16

Inherit _See_ Inheritance

Inheritance

exaggerated detailed 44

multiple 48

of consistency constraints 87

of enumerations _37_, 53

of numeric value domains 50

of relationships 80

of structures 68

of topics 20, 47

of views 94

on a larger scale 20, 47

principles 43

Inspection 93

Instance 11

Integer 49

Internet address _See_ URI

ISO 19100 29

ISO 3166 103

J

Join 91

L

Length of time _32_, _35_, 71

Line 63

directed 64

especially formed 99

in space 66

structure 63, 69, 99

M

Meta data 58

Model _See_ Data model

Model-based approach 30

Modul 17

Moment in time _33_, 74

Multilingualism 69

in data transfer 105

object characteristics _34_

of data models 95

Multiple inheritance 48

N

Numeric data type _36_, 50

O

Object 11

Object catalog 11

Object class 11

Object identification See Identification

Object Management Group 30

OMG 30

OMT 27

OOSE 27

Overlap

with lines 64

with surfaces _See_ Tessellation

P

Package 17

Parameter 97

Plausibility 84

Pointer _See_ Relationship

Polymorph reading 24, 103, 113

Polymorphism 47

at the transfer 24, 103, 113

Precision

of lines 64, 100

of numeric types 49

Projection

of coordinates 57

of views 91

Property 13

abstract 51

inherit _See_ Inheritance

Proxy object 103

Put to use what already exists 16

R

Radius 100

Real (floating point number) 49

Reference _See_ Relationship

Reference system

of coordinates 63

of moments in time 75

Relationship 11, _35_, 75

aggregation 76

and inheritance 80

association 76

association class _36_

composition _39_, 76

derivable _38_, 82

force 76, 82

multiple _36_, 78

ordered 79

topic independence 88

Replica 103

Restriction _See_ Inheritance

Role _35_, 75

S

Schema _See_ Data model

Segment 63

Special case _See_ Inheritance

Spline 99

Straight segment 63, 99

String _34_, 55

Structure 68

and inheritance 68

as aggregation 93

as inspection 93

Sub class _See_ Inheritance

Sub-enumeration 54

Substitute 103

Super class _See_ Inheritance

Surface 64

Surveying 29, 112

Sustainability 102

System neutrality 97

T

Table 11

Tessellation _40_, 66

Text _34_, 55

Topic 19, 87

Transfer 15, 101

and multilingualism 105

format 22

full 16, 104

identification 102

incremental 103, 104

model based 22, 112

of lines 99

of test data _41_

polymorph reading 103

system independent 112

*system specific* 23

to a higher position 24

with a conversion program 24, 97

Tuple 11

Type _See_ Data type

Type of attribute _See_ Data type

Types _35_, 51

U

Umlauts 24

Undefined 55

Underground cadastre 29

Unified Modeling Language 27, 112

UML-Editor 30

Union 93

Uniqueness _34_, 84, 104

Unit _32_, 50

Update 16, 111

Upper class _See_ Inheritance

URI _38_, 55

V

Value domain 13, _32_, 56

geometrical 63

numeric _36_, 50

structured 73

View 25, _38_, 90

aggregation 93

and inheritance 94

building step by step 93

formation law 90

inspection 93

join 91

union 93

X

XML 29, 101, 113
