[#_3]
== Möglichkeiten zur Beschreibung von Daten

[#_3_1]
=== Beschreibung als Grafik: Unified Modeling Language UML

Ein Diagramm eignet sich gut dafür, sich selber und anderen schnell einen Überblick zu einem Modell zu verschaffen. Daher werden in der Informatik bereits seit Mitte der 1970er Jahre graphische Notationen eingesetzt, um Modelle zu visualisieren. Allerdings konnte man sich lange Zeit nicht auf eine einheitliche Darstellungsweise einigen, so dass dutzende Notationen gleichzeitig im Einsatz waren. Schliesslich begannen sich zu Beginn der 1990er Jahre drei Methoden (Booch, OMT und OOSE) durchzusetzen. Deren Urheber, die so genannten «drei Amigos», konnten sich 1995/96 auf eine einzige Modellierungssprache einigen, die _Unified Modeling Language (UML)_. Seit 1997 wird die UML als Standard von einem Industriekonsortium, der _Object Management Group_, verwaltet und gepflegt.

Die UML ist flexibel und vielseitig einsetzbar. Wer mit ihrer Schreibweise vertraut ist, kann auf einen Blick Modelle aus den unterschiedlichsten Anwendungsbereichen erfassen. Die Sprache eignet sich übrigens nicht nur zum Modellieren von Daten (mittels der in diesem Papier vorgestellten Klassendiagramme). Sie umfasst auch Elemente für weitere Aspekte eines Systems, zum Beispiel die Aufteilung in Komponenten oder Szenarien für die Benut­zung.

Ein wichtiger Faktor für den Erfolg der UML ist ihre Anpassungsfähigkeit: Für viele An­wendungen stellt die Sprache eine ausreichende Infrastruktur bereit, es ist aber jederzeit möglich, die Sprache mit klar definierten, ebenfalls standardisierten Erweiterungsmecha­nismen an eigene Bedürfnisse anzupassen.

Eine visuelle Sprache wie die UML besitzt zwar viele Vorteile, sie ist aber nicht für alle Anwendungen das ideale Mittel. Sobald es nämlich darum geht, die Details eines grossen und komplexen Modells festzulegen, kann eine Zeichnung auch unübersichtlich und verwirrend werden. Auch ist eine graphische Darstellung eher unpraktisch, um zum Beispiel ein Computersystem einzurichten. In manchen Fällen eignet sich daher eine Textform besser: Die Modelle werden in einer genormten Sprache als Text aufgeschrieben und können so von Mensch und Computer gleichermassen verstanden werden. Natürlich kann das Bild gleichzeitig weiterhin für den groben Überblick verwendet werden. Zurzeit sind Vorschläge für eine rein textuelle Schreibweise der UML in Diskussion, es wurde jedoch bisher noch kein entsprechender Standard verabschiedet.

[#_3_2]
=== Beschreibung als Text: INTERLIS

In der Schweiz wurde schon vor langem erkannt, dass ein modellbasierter Ansatz beträchtliche Vorteile mit sich bringt. Im Rahmen der amtlichen Vermessung wurde daher 1991 die textuelle Modellierungssprache INTERLIS entwickelt. Ende der 1990er Jahre wurde INTERLIS 2 ausgearbeitet, welches die erste Version erweitert und modernisiert. Ein halbes Dutzend Spezialisten aus Forschung, Verwaltung und Industrie stellte dabei sicher, dass die Sprache den Anforderungen der Praxis gerecht wird. Zudem wurde grosser Wert darauf gelegt, dass einige Besonderheiten gut unterstützt werden, die sich aus der Anwendung ergeben:

* Datenmodelle können mit INTERLIS präzise und in einem sehr hohen Detaillierungs­grad beschrieben werden. Dadurch kann ein INTERLIS-Modell direkt zum Bestandteil eines Ausschreibungstextes, eines Vertrags oder einer Verordnung werden, und es ist auch möglich, ein Programmpaket anhand eines INTERLIS-Modells zu konfigurieren.
* INTERLIS umfasst nicht nur eine Sprache zum Modellieren der Daten, sondern auch ein Verfahren, mit dem aus einem Modell das Transferformat abgeleitet wird, welches zum Austausch der modellierten Daten benutzt wird. Dies ist deswegen besonders wichtig, weil geographische Daten sehr aufwändig zu erfassen und entsprechend wert­voll sind. Zudem liegt ihre Lebensdauer im Bereich von Jahrzehnten, ist also deutlich länger als jene von Informatiksystemen, die meist schon nach wenigen Jahren ver­alten. Die teuer erhobenen Daten können nur geschützt werden, indem sie in einer Form gehalten werden, die unabhängig von einem konkreten Programm ist.
* Obwohl INTERLIS natürlich auch für Anwendungen benutzt werden kann, die keinerlei geographischen Bezug besitzen, eignet es sich für räumliche Daten besonders gut. Geometrie wird bereits im Kern der Sprache unterstützt. Auch wurden Vorkehrungen getroffen, aufgrund derer die Qualität und Plausibilität von angelieferten Daten automa­tisch geprüft werden können.
* INTERLIS-Datenmodelle sind klar strukturiert: Ein Modell ist in Themen gegliedert, die ihrerseits Objektklassen umfassen. Zur Beschreibung einer Objektklasse gehören die Objekteigenschaften sowie Konsistenz- und Plausibilitätsbedingungen. Sowohl auf Mo­dell- als auch auf Themenstufe können allgemein benutzbare Konstrukte (z.B. Ein­heiten, Wertebereiche, Hilfs-Strukturen, etc.) deklariert werden.
* Die föderalistische Struktur der Schweiz mit ihren 26 Kantonen und Halbkantonen, die ihrerseits in weitere Verwaltungseinheiten gegliedert sind, stellt besondere Anforderungen an eine Modellierungssprache. INTERLIS 2 erlaubt es, dass die Beteiligten ein gemeinsames Kernmodell gemäss ihren regionalen Bedürfnissen ausbauen und verfeinern können. Dabei bleibt der problemlose Austausch der Daten auch dann gewährleistet, wenn lokal unterschiedliche Modelle im Einsatz sind. Zudem unterstützt INTERLIS, dass Modelle und Daten in verschiedenen Sprachen abgefasst sein können. Damit kann jeder Landesteil seine jeweilige Amtssprache verwenden.

INTERLIS und UML ergänzen sich: UML-Diagramme sind schnell aufgezeichnet und ideal für eine grobe Übersicht. Mit INTERLIS können die Details präzise und dennoch leicht verständlich festgehalten werden, zudem werden Anforderungen der föderalistischen Geo­daten-Praxis speziell unterstützt. Es existieren Werkzeuge, die ein UML-Klassendiagramm automatisch in eine textuelle INTERLIS-Beschreibung umwandeln können. Auch der um­gekehrte Schritt, das Darstellen eines INTERLIS-Modells in der UML-Schreibweise, kann automatisch erfolgen.

[#_3_3]
=== Standardisierte Datenmodelle

Es macht wenig Sinn, jedes Datenmodell vollständig von Grund auf neu zu erstellen. Stattdessen können vordefinierte Modelle benutzt und verfeinert werden. Auf verschiedenen Stufen wurden und werden Modelle entwickelt, auf denen Anwendungen aufbauen können:

* *International* – Im Rahmen von internationalen Normierungsbestrebungen wurde unter anderem ein sehr umfassendes Modell für Basis-Geometrietypen (ISO 19107) entwickelt. Es sind Bestrebungen in Gang, einen Kern herauszuschälen, welcher den wichtigsten Anforderungen der Praxis entspricht (ISO 19137). Hierfür werden die räumlichen Konzepte mehrerer verbreiteter Modellierungssprachen analysiert, unter anderem auch jene von INTERLIS. Wer sich Gedanken darüber macht, wie etwa Kegelschnittflächen oder Dreiecksnetze zu modellieren sind, ist beraten, sich in die Normdokumente bzw. die entsprechenden Entwürfe einzulesen. Die ISO-19100-Serie umfasst auch Datenmodelle für Zeitabschnitte (ISO 19108), Metadaten (ISO 19115), Dienste (ISO 19119), und anderes mehr. Allerdings sind viele dieser Normen noch im Entwurfsstadium, und es besteht noch wenig Erfahrung, wie tauglich sie in der Praxis sind.
* *National* – In der Schweiz existieren für mehrere Anwendungsbereiche standardi­sierte Modelle. Teilweise ist ihre Verwendung in Gesetzen und Verordnungen vorge­schrieben. Für die amtliche Vermessung, für Leitungsnetze und seit kurzem auch für geo-codierte Adressen wurden landesweit gültige Modelle ausgearbeitet.
* *Branchenverbände* – Eine weitere Quelle für Datenmodelle, auf denen eigene An­wendungen aufbauen können, sind die Branchenverbände. So hat der Schweizerische Ingenieur- und Architektenverband SIA ein INTERLIS-Modell für den Leitungskataster (Abwasser, Gas, Wasser, Fernwärme, Elektrizität, Telecom, Kabelkommunikation) aus­gearbeitet.
* *INTERLIS* – Für einige wenige, sehr grundlegende Bereiche gibt INTERLIS Standardmodelle vor. So wird mit den INTERLIS-Werkzeugen unter anderem ein Modell mit Einheiten (units.ili) ausgeliefert, in dem Meter, Newton, Dezibel und ähnliches definiert werden.

Die Schweizer Modelle werden nach Möglichkeit mit den ISO-Normen in Einklang gebracht. Beispielsweise wurde ein nationales Modell für Metadaten zu geographischen Daten (z.B. Herkunft, Qualität etc.) entsprechend ISO 19115 ausgearbeitet. Das Modell liegt als INTER­LIS-Beschreibung vor.

Dank der Verfeinerungs-Mechanismen von INTERLIS kann eine konkrete Anwendung auf ein bereits bestehendes Datenmodell zurückgreifen, ohne dass es _tel quel_ übernommen werden müsste.

[#_3_4]
=== Formate zum Datenaustausch

Alle Daten müssen irgendwann in einem bestimmten Format gespeichert werden, damit sie gelagert und zwischen Softwarepaketen ausgetauscht werden können. Neuere Austauschformate sind alle auf der _Extensible Markup Language_ (XML) aufgebaut, einem Format, das wegen seinem extrem einfachen Aufbau, der Verwandtschaft mit HTML (dem Format von Webseiten) und der Abstammung von SGML (einem früher häufig benutzten Format) grosse Verbreitung gefunden hat.

Beispielsweise ist die _Geographic Markup Language_ (GML) ein fest definierter XML-Dialekt, der von OpenGIS, einem Herstellerkonsortium von GIS-Software, propagiert wird. Dagegen schreibt INTERLIS keinen bestimmten XML-Dialekt vor, sondern gibt Regeln, anhand derer das Austauschformat automatisch aus dem jeweiligen Datenmodell abgeleitet wird.

An sich ist die Frage des Datenformats sekundär: Solange zu übertragende Daten auf ähn­lichen Modellen aufbauen, ist es mit geringem Aufwand möglich, die Daten von einem For­mat in ein anderes umzuwandeln.

[#_3_5]
=== Wichtige Informationsquellen

Weitere Informationen können unter anderem von folgenden Quellen bezogen werden:

* *http://www.interlis.ch[www.interlis.ch]* – Das Internet-Portal zu INTERLIS verweist auf Unterlagen, Kurse usw. im Zusammenhang mit INTERLIS. Von dieser Adresse können auch die Spezifikation des Standards und der vorliegende Text elektronisch bezogen werden. Schliesslich sind auf dieser Webseite auch Werkzeuge verfügbar. Zur Zeit sind dies ein Computerprogramm, mit dem INTERLIS-Modelle in der graphischen UML-Notation editiert werden können («UML-Editor»), und eine Softwarebibliothek zum Einlesen, Prüfen, Verändern und Ausgeben von INTERLIS-Modellen («INTERLIS-Compiler»).
* *http://www.omg.org[www.omg.org]* – Von der Webseite der Object Management Group kann die Definition der Unified Modeling Language bezogen werden. Ausserdem sind dort allgemeine Unterlagen (wie Schulungsmaterial oder Pressetexte) zum Modellbasierten Ansatz zu finden.
* *http://www.w3.org/[www.w3.org]* – Das _World Wide Web Consortium_ verwaltet unter anderem auch die Spezifikation von XML.

