[#_3_4]
=== Formate zum Datenaustausch

Alle Daten müssen irgendwann in einem bestimmten Format gespeichert werden, damit sie gelagert und zwischen Softwarepaketen ausgetauscht werden können. Neuere Austauschformate sind alle auf der _Extensible Markup Language_ (XML) aufgebaut, einem Format, das wegen seinem extrem einfachen Aufbau, der Verwandtschaft mit HTML (dem Format von Webseiten) und der Abstammung von SGML (einem früher häufig benutzten Format) grosse Verbreitung gefunden hat.

Beispielsweise ist die _Geographic Markup Language_ (GML) ein fest definierter XML-Dialekt, der von OpenGIS, einem Herstellerkonsortium von GIS-Software, propagiert wird. Dagegen schreibt INTERLIS keinen bestimmten XML-Dialekt vor, sondern gibt Regeln, anhand derer das Austauschformat automatisch aus dem jeweiligen Datenmodell abgeleitet wird.

An sich ist die Frage des Datenformats sekundär: Solange zu übertragende Daten auf ähn­lichen Modellen aufbauen, ist es mit geringem Aufwand möglich, die Daten von einem For­mat in ein anderes umzuwandeln.

[#_3_5]
