[#_3_2]
=== Beschreibung als Text: INTERLIS

In der Schweiz wurde schon vor langem erkannt, dass ein modellbasierter Ansatz beträchtliche Vorteile mit sich bringt. Im Rahmen der amtlichen Vermessung wurde daher 1991 die textuelle Modellierungssprache INTERLIS entwickelt. Ende der 1990er Jahre wurde INTERLIS 2 ausgearbeitet, welches die erste Version erweitert und modernisiert. Ein halbes Dutzend Spezialisten aus Forschung, Verwaltung und Industrie stellte dabei sicher, dass die Sprache den Anforderungen der Praxis gerecht wird. Zudem wurde grosser Wert darauf gelegt, dass einige Besonderheiten gut unterstützt werden, die sich aus der Anwendung ergeben:

* Datenmodelle können mit INTERLIS präzise und in einem sehr hohen Detaillierungs­grad beschrieben werden. Dadurch kann ein INTERLIS-Modell direkt zum Bestandteil eines Ausschreibungstextes, eines Vertrags oder einer Verordnung werden, und es ist auch möglich, ein Programmpaket anhand eines INTERLIS-Modells zu konfigurieren.
* INTERLIS umfasst nicht nur eine Sprache zum Modellieren der Daten, sondern auch ein Verfahren, mit dem aus einem Modell das Transferformat abgeleitet wird, welches zum Austausch der modellierten Daten benutzt wird. Dies ist deswegen besonders wichtig, weil geographische Daten sehr aufwändig zu erfassen und entsprechend wert­voll sind. Zudem liegt ihre Lebensdauer im Bereich von Jahrzehnten, ist also deutlich länger als jene von Informatiksystemen, die meist schon nach wenigen Jahren ver­alten. Die teuer erhobenen Daten können nur geschützt werden, indem sie in einer Form gehalten werden, die unabhängig von einem konkreten Programm ist.
* Obwohl INTERLIS natürlich auch für Anwendungen benutzt werden kann, die keinerlei geographischen Bezug besitzen, eignet es sich für räumliche Daten besonders gut. Geometrie wird bereits im Kern der Sprache unterstützt. Auch wurden Vorkehrungen getroffen, aufgrund derer die Qualität und Plausibilität von angelieferten Daten automa­tisch geprüft werden können.
* INTERLIS-Datenmodelle sind klar strukturiert: Ein Modell ist in Themen gegliedert, die ihrerseits Objektklassen umfassen. Zur Beschreibung einer Objektklasse gehören die Objekteigenschaften sowie Konsistenz- und Plausibilitätsbedingungen. Sowohl auf Mo­dell- als auch auf Themenstufe können allgemein benutzbare Konstrukte (z.B. Ein­heiten, Wertebereiche, Hilfs-Strukturen, etc.) deklariert werden.
* Die föderalistische Struktur der Schweiz mit ihren 26 Kantonen und Halbkantonen, die ihrerseits in weitere Verwaltungseinheiten gegliedert sind, stellt besondere Anforderungen an eine Modellierungssprache. INTERLIS 2 erlaubt es, dass die Beteiligten ein gemeinsames Kernmodell gemäss ihren regionalen Bedürfnissen ausbauen und verfeinern können. Dabei bleibt der problemlose Austausch der Daten auch dann gewährleistet, wenn lokal unterschiedliche Modelle im Einsatz sind. Zudem unterstützt INTERLIS, dass Modelle und Daten in verschiedenen Sprachen abgefasst sein können. Damit kann jeder Landesteil seine jeweilige Amtssprache verwenden.

INTERLIS und UML ergänzen sich: UML-Diagramme sind schnell aufgezeichnet und ideal für eine grobe Übersicht. Mit INTERLIS können die Details präzise und dennoch leicht verständlich festgehalten werden, zudem werden Anforderungen der föderalistischen Geo­daten-Praxis speziell unterstützt. Es existieren Werkzeuge, die ein UML-Klassendiagramm automatisch in eine textuelle INTERLIS-Beschreibung umwandeln können. Auch der um­gekehrte Schritt, das Darstellen eines INTERLIS-Modells in der UML-Schreibweise, kann automatisch erfolgen.

[#_3_3]
