[#_3_1]
=== Beschreibung als Grafik: Unified Modeling Language UML

Ein Diagramm eignet sich gut dafür, sich selber und anderen schnell einen Überblick zu einem Modell zu verschaffen. Daher werden in der Informatik bereits seit Mitte der 1970er Jahre graphische Notationen eingesetzt, um Modelle zu visualisieren. Allerdings konnte man sich lange Zeit nicht auf eine einheitliche Darstellungsweise einigen, so dass dutzende Notationen gleichzeitig im Einsatz waren. Schliesslich begannen sich zu Beginn der 1990er Jahre drei Methoden (Booch, OMT und OOSE) durchzusetzen. Deren Urheber, die so genannten «drei Amigos», konnten sich 1995/96 auf eine einzige Modellierungssprache einigen, die _Unified Modeling Language (UML)_. Seit 1997 wird die UML als Standard von einem Industriekonsortium, der _Object Management Group_, verwaltet und gepflegt.

Die UML ist flexibel und vielseitig einsetzbar. Wer mit ihrer Schreibweise vertraut ist, kann auf einen Blick Modelle aus den unterschiedlichsten Anwendungsbereichen erfassen. Die Sprache eignet sich übrigens nicht nur zum Modellieren von Daten (mittels der in diesem Papier vorgestellten Klassendiagramme). Sie umfasst auch Elemente für weitere Aspekte eines Systems, zum Beispiel die Aufteilung in Komponenten oder Szenarien für die Benut­zung.

Ein wichtiger Faktor für den Erfolg der UML ist ihre Anpassungsfähigkeit: Für viele An­wendungen stellt die Sprache eine ausreichende Infrastruktur bereit, es ist aber jederzeit möglich, die Sprache mit klar definierten, ebenfalls standardisierten Erweiterungsmecha­nismen an eigene Bedürfnisse anzupassen.

Eine visuelle Sprache wie die UML besitzt zwar viele Vorteile, sie ist aber nicht für alle Anwendungen das ideale Mittel. Sobald es nämlich darum geht, die Details eines grossen und komplexen Modells festzulegen, kann eine Zeichnung auch unübersichtlich und verwirrend werden. Auch ist eine graphische Darstellung eher unpraktisch, um zum Beispiel ein Computersystem einzurichten. In manchen Fällen eignet sich daher eine Textform besser: Die Modelle werden in einer genormten Sprache als Text aufgeschrieben und können so von Mensch und Computer gleichermassen verstanden werden. Natürlich kann das Bild gleichzeitig weiterhin für den groben Überblick verwendet werden. Zurzeit sind Vorschläge für eine rein textuelle Schreibweise der UML in Diskussion, es wurde jedoch bisher noch kein entsprechender Standard verabschiedet.

[#_3_2]
