[#_5_2]
=== Ererbtes verfeinern

Hundert Zeichen für den Namen einer Bahn mag im allgemeinen Fall ja angemessen sein. Schliesslich war auch schon einmal die Rede davon gewesen, einen «Kinder- und- Familien-Schlittenlift Region Ilishorn» zu betreiben. Allerdings entschied man sich dann doch noch im letzten Moment für den Namen «Ponylift», zur grossen Erleichterung des Verkehrsvereins.

Aber eine Tramlinie mit hundert Buchstaben? Hier reichen fünf Zeichen definitiv aus.

[#listing-05_02-01]
.link:#listing-05_02-01[Listing 05.02-01]
[source]
----
CLASS Bahn =
  Name: TEXT*100;
END Bahn;

CLASS Bergbahn EXTENDS Bahn =
  LageTalstation: LandesKoord;
  LageBergstation: LandesKoord;
END Bergbahn;

CLASS Tramlinie EXTENDS Bahn =
  Name (EXTENDED): TEXT*5;
END Tramlinie;
----

Abbildung 27: Für den Namen einer Tramlinie reichen fünf Zeichen aus: Der Typ der Eigenschaft «Name» wird von der Unterklasse verfeinert (präzisiert). Rechts wiederum dasselbe in der Schreibweise von INTERLIS.

Die präzisierte, verfeinerte Angabe muss mit der übernommenen verträglich sein. Beispiels­weise darf die maximal erlaubte Namenslänge bei der Tramlinie nicht länger als bei der all­gemeinen Bahn sein.

[NOTE]
====
Unterklassen können ererbte Eigenschaften *verfeinern*. Die präzisierten An­gaben dürfen aber nicht im Widerspruch zu den übernommenen stehen: sie müs­sen mit den Definitionen der Oberklasse *verträglich* sein.

_Andernfalls könnte es zu einer Unterklasse Objekte geben, die nicht zur Menge aller Objekte der Oberklasse gehören._
====

[#_5_3]
