[#_6_4]
=== Ilistaler halten sich kurz – Zeichenketten und ihre Erbregeln

Bezeichnungen können grundsätzlich beliebig lange Namen enthalten. Der nationale Verband hat jedoch festgelegt, dass der Name einer Bergbahn höchstens 100 Zeichen aufweisen darf. In der Regel sind die Namen natürlich durchaus kürzer, man wollte einfach sicher gehen.

[source]
----
STRUCTURE Bahnbezeichnung EXTENDS Bezeichnung =
  Name (EXTENDED): TEXT*100;
END Bahnbezeichnung;
----

Ist die Länge eines Text-Attributes beliebig oder noch vollkommen unbekannt, kann auf die Angabe der Länge verzichtet werden. Ist es klar, dass die Länge im Rahmen einer Klassenerweiterung noch festgelegt wird, wird das Attribut als abstrakt bezeichnet:

[source]
----
Beschreibung (ABSTRACT): TEXT;
----

Manche Bahnen im Ilistal haben eine Web-Kamera installiert, die laufend die Umgebung der Bergstation aufnimmt. Interessierte Touristen können so sehen, ob sich die Reise lohnt. Die Internet-Adresse des aktuellen Bildes ist ebenfalls eine (etwas besondere) Art von Text.

[source]
----
CLASS IhBBergbahn =
  ...
  BildBergstation: URI;
  ...
END IhBBergbahn;
----

Internet-Adressen haben aber nichts mit einem Schweizer Kanton zu tun – oder wenn schon, dann allenfalls mit Genf, wo am CERN der erste Web-Browser entwickelt wurde. URI ist schlicht die Abkürzung von _Uniform Resource Identifier._ Die meist für Web-Seiten benutzten _Uniform Resource Locators (URLs)_ sind spezielle URIs.

[#_6_5]
