[#_6_1]
=== Taler und Groschen – Numerische Datentypen

[#_6_1_1]
==== Wertebereich

Ein Einzelbillett für eine einfache Fahrt mit der Standseilbahn auf das Ilishorn kostet 10 Ah­länder Taler, ein Jahressportpass 635 Taler. Wie soll nun der Preis eines Billettes modelliert werden?

Wer sich an Programmiersprachen gewohnt ist, denkt sicher sofort an ganze Zahlen («Integer») oder Fliesskommazahlen («Real»). Bei vielen Programmiersprachen und Daten­banken lässt sich festlegen, wie viel Speicherplatz eine Zahl benötigt; hieraus folgen Grösse und Genauigkeit der speicherbaren Zahlen («short integer», «long integer», «double precision», etc.). Man überlegt sich dann, in welchem Bereich die Werte etwa liegen können, und wählt die passende Speicherform.

Bei der Modellierung auf konzeptueller Stufe möchte man sich aber eigentlich nicht um die Speicherform kümmern. Es ist aber möglich, den höchsten und den tiefsten zulässigen Wert anzugeben und dabei gleich noch die Stellenzahl sowie den Exponenten festzulegen.

Da sich die Preise zwischen 10 und 635 Talern bewegen, könnte man also schreiben:

[source]
----
Preis: 10 .. 635;
----

Damit würde man aber auch festlegen, dass ein Preis nie kleiner als 10 Taler und nie grösser als 635 Taler sein kann. Das möchte man natürlich nicht. Als untere Schranke ist 0 plausibel. Aber die obere Schranke? Mehr als 10'000 Taler werden es ja kaum sein. Also 10'000? Wo eine Schranke auf Grund der Anwendung nicht genau festgelegt werden kann, macht es jedenfalls keinen Sinn, den Wert so zu wählen, dass eine kürzere Speicherform (z.B__. short integer__ mit Werten zwischen –32768 und 32767) gerade nicht mehr ausreicht.

Dabei ist es natürlich auch wichtig zu überlegen, wie viele Nachkommastellen nötig sind. Wenn die Preise auch Groschen aufweisen können, werden die Schranken eben mit jeweils zwei Nachkommastellen festgelegt. Bei einem Attribut, das z.B. ein Investitionsbudget dar­stellt, möchte man sich nur mit Millionen abgeben; wo es nur um Grössenordnungen geht, reichen zwei Ziffern. Diese können sich aber auf Tausend, eine Million oder gar eine Milliarde beziehen.

[source]
----
Preis: 0.00 .. 9999.99;
Budget: 0.00E6 .. 999.99E6;
Bruttosozialprodukt: 0.0E0 .. 9.9E20;
----

Die Anzahl der Stellen bezeichnet die Genauigkeit: «4.3 Millionen» (4.3E6 = 4.3 · 106) ist eine weniger genaue Angabe als «4300000».

[#_6_1_2]
==== Einheiten

Sind das jetzt Taler, Franken, Euro oder Dollar? Die Einheit ist – nicht nur beim Geld – von entscheidender Bedeutung. Darum ist es empfehlenswert, die Einheit nicht nur als Kommentar oder als Teil des Attributnamens anzugeben, sondern als Bestandteil des Typs:

[source]
----
UNIT
  Taler EXTENDS MONEY;

CLASS Billettart =
  Preis: 0 .. 9999 [Taler];
END Billettart;
----

Taler (oder Schweizerfranken, Euro, Dollar, etc.) werden als Einheit definiert und können dann bei der Definition eines numerischen Typs benutzt werden. Die meisten gängigen Einheiten (darunter auch CHF, EUR, USD) müssen jedoch nicht selbst definiert werden, sondern stehen über das spezielle Einheiten-Modell (units.ili, vgl. Abschnitt <<_3_3>>) zur Verfügung.

[WARNING]
Im Interesse der Klarheit wird empfohlen, immer Einheiten anzugeben. Das INTERLIS-Einheitenmodell umfasst neben zahlreichen physikalischen Einheiten auch solche für verbreitete Währungen und für Anzahl, Prozente und Promille.

[#_6_1_3]
==== Numerische Typen erben

Da die Ilishornbahnen nie Billette abgeben werden, die mehr als tausend Taler kosten, könnte man auf die Idee kommen, dies in einer eigenen Klasse zu definieren:

[source]
----
CLASS Billettart (EXTENDED) =
  Preis (EXTENDED): 0 .. 1000 [Taler];
END Billettart;
----

In dieser Anwendung macht dieses konkrete Beispiel eher wenig Sinn. Es gibt aber durchaus Fälle in der Praxis, wo es sinnvoll ist, den ererbten Wertebereich einzuschränken.

Die Ilistaler dürfen nun allerdings nicht die Wertebereiche des nationalen Modells beliebig verändern: Es gilt das Prinzip, dass jeder Ilistaler Wert auch im Basismodell des Nationalverbands zulässig sein muss. Sonst wäre nicht mehr sichergestellt, dass der nationale Verband problemlos Daten aus dem Ilistal übernehmen kann.

Eine Preisangabe 0 .. 1000 ist also eine zulässige Einschränkung des national vorgesehe­nen Bereichs 0 .. 9999. Würde man den Wertebereich im Ilistal aber ausdehnen – etwa mit der Angabe 0 .. 15000 – dann wären Billettarten, die zwischen 10000 und 15000 Taler kos­ten, aus der Sicht des nationalen Verbandes nicht korrekt. Eine solche Definition ist darum unzulässig.

Die Ilistaler wollen auch die Möglichkeit haben, Billette auszugeben, deren Preis nicht zwin­gend ein voller Talerbetrag ist. Man möchte folgende Definition schreiben:

[source]
----
CLASS Billettart (EXTENDED) =
  Preis (EXTENDED): 0.00 .. 1000.00 [Taler];
END Billettart;
----

Aber ist das mit dem Basismodell verträglich? Ja, denn jeder Wert gemäss Ilistaler Modell (z.B. 7.35) kann mit mathematischer Rundung auf einen korrekten Wert des nationalen Modells abgebildet werden (z.B. 7).

Die Definition wäre dann unzulässig, wenn sie Werte umfassen würde, die gerundet das Basismodell verletzen. Beispielsweise würde ein Maximalwert von 9999.99 nach dem Runden zu 10000 – dies wäre mehr als die vom nationalen Verband vorgegebenen 9999. Dagegen könnten die Ilistaler einen Bereich 0.00 .. 9999.49 definieren, ohne dem Basis­modell zu widersprechen, denn 9999.49 ergibt nach der Rundung wieder 9999.

Ebenfalls unzulässig ist es, im spezialisierten Modell auf Genauigkeit zu verzichten. Würde das nationale Tourismusmodell zum Beispiel einen Bereich von 0.00 .. 1000.00 vorsehen, könnten die Ilistaler in ihrer Spezialisierung nicht die Angabe 0 .. 1000 machen.

Und noch etwas: Die Einheiten der Erweiterung müssen immer mit derjenigen der Basis übereinstimmen!

[#_6_1_4]
==== Schranken noch unbekannt

Kann der nationale Verband festlegen, welcher Preis für ein Billett zulässig ist? Sind die Schranken noch völlig unbekannt, kann – im Rahmen abstrakter Attribute – auf ihre An­gabe verzichtet werden. Es ist aber möglich, dennoch bereits eine Einheit festzulegen.

[source]
----
Preis (ABSTRACT): NUMERIC [Ahland.Taler];
----

Vielleicht ist sogar die Einheit noch unklar. Man weiss erst, dass es sich z.B. um eine Währung handelt.

[source]
----
Preis (ABSTRACT): NUMERIC [MONEY];
----

Damit ist immerhin der Charakter der Einheit festgelegt. In einer Erweiterung können damit nur noch Einheiten definiert werden, die Konkretisierungen der abstrakten Einheit MONEY sind (zu abstrakten Eigenschaften siehe auch Abschnitt <<_5_4>>).

[source]
----
Preis (EXTENDED): 0 .. 10000 [CHF]; !! erlaubt
Preis (EXTENDED): 0 .. 2000 [USD]; !! erlaubt
Preis (EXTENDED): 0 .. 1000 [m]; !! verboten, da Meter eine Konkre-
                                  !! tisierung von LENGTH und nicht
                                  !! von MONEY ist.
----

[#_6_2]
