[#_6_3]
=== Gibt es auch hellblaue Skipisten? – Strukturierte Aufzählungen

[#_6_3_1]
==== Gewöhnliche Aufzählungen und ihr Erbrecht

Um den Schwierigkeitsgrad von Skipisten grob zu beschreiben, wurden drei Farben gewählt: blau, rot, schwarz. Es soll nur diese und keine anderen Schwierigkeitsgrade geben. Zudem sind sie geordnet. Blau bezeichnet eine einfache Piste, eine rote Piste ist schwieriger als eine blaue, eine schwarze am anspruchsvollsten. Dies wird mit der folgenden Definition be­schrieben:

[#listing-06_03-01]
.link:#listing-06_03-01[Listing 06.03-01]
[source]
----
CLASS Piste =
  Schwierigkeitsgrad: (blau, rot, schwarz: FINAL) ORDERED;
END Piste;
----

Würde die FINAL-Angabe fehlen, könnte die Aufzählung in einer Erweiterung noch ergänzt werden. Zum Beispiel könnte dies bei der Art von Bergbahnen Sinn machen:

[#listing-06_03-02]
.link:#listing-06_03-02[Listing 06.03-02]
[source]
----
!! Modell des Nationalen Tourismusverbandes
CLASS Bergbahn =
  Art: (Zahnradbahn, Standseilbahn, Luftseilbahn,
       Skilift, Sessellift, Gondelbahn);
END Bergbahn;

!! Modell Ilistal
CLASS IhBBergbahn EXTENDS Bergbahn =
  Art (EXTENDED): (Schneebus);
END IhBBergbahn;
----

In der erweiterten Klasse wird der Aufzählung noch das Element Schneebus – das neuste vom Neuen – am Ende der bisherigen Aufzählung beigefügt. Aber was fängt der nationale Tourismusverband damit an? Dort ist «Schneebus» doch ein unbekannter Wert.

[NOTE]
Jede (horizontale) Erweiterung kann durch weitere Werte ergänzt werden, solange dies nicht ausdrücklich mit *FINAL* ausgeschlossen wird. Interessiert sich jemand für die Werte nur allgemein gemäss der Basisklasse, werden diese Werte alle in den Wert *OTHER* übersetzt.

Für die Basisklasse ist der Wert Schneebus (und allfällige weitere Werte) nur noch als OTHER erkennbar. Wird jedoch FINAL angegeben, kann der Wert OTHER nicht mehr auftreten. Ist eine Aufzählung zyklisch (*CIRCULAR*) definiert, sind solche Ergänzungen nie möglich, heisst doch zyklisch, dass nach dem höchsten Wert wieder der niedrigste kommt und man sonst gar nicht wüsste, welches der höchste ist.

[#listing-06_03-03]
.link:#listing-06_03-03[Listing 06.03-03]
[source]
----
Windrichtung: (N, NE, E, SE, S, SW, W, NW) CIRCULAR;
----

[#_6_3_2]
==== Unteraufzählungen

Man hatte also beschlossen, die verschiedenen Arten von Bergbahnen nicht mit einer ganzen Landschaft von Klassen zu modellieren. Aber die Bahnfreunde waren nicht recht einverstanden: Das Stangensystem der Zahnradbahnen könnte ja vielleicht doch noch irgendwann einmal von Interesse sein...

Für jeden Wert einer Aufzählung kann eine Unteraufzählung definiert werden. Dies kann direkt innerhalb der Basisdefinition oder erst in einer Erweiterung erfolgen.

[#listing-06_03-04]
.link:#listing-06_03-04[Listing 06.03-04]
[source]
----
CLASS IhBBergbahn EXTENDS Bergbahn =
  Art (EXTENDED): (Zahnradbahn (Riggenbach, Abt, vonRoll));
END IhBBergbahn;

Wochentag: (Werktag (Montag, Dienstag, Mittwoch,
                     Donnerstag, Freitag, Samstag),
            Sonntag);
----

Wird eine solche Unteraufzählung in einer Erweiterung definiert, ist sie aus der Sicht der Basis einfach nicht von Belang. Aus der Sicht des nationalen Tourismusverbands würde also auch eine Riggenbach-Zahnradbahn eine Zahnradbahn sein.

Auch Unteraufzählungen können wieder um weitere Werte ergänzt werden, sofern ihr letzter Wert nicht als FINAL erklärt wurde. Die einzelnen Werte einer Unteraufzählung können zudem wiederum durch Unteraufzählungen präzisiert werden, so dass ganze Aufzählungs­bäume entstehen.

[#_6_4]
