[#_6_5]
=== Windstille – Fakultative und obligatorische Attribute

Als aktuelle Betriebsdaten werden auch aktuelle Wetterdaten wie Temperatur sowie Richtung und Stärke des Windes gemeldet. Bei Windstille macht die Angabe der Windrichtung keinen Sinn. Die anderen Angaben sollen immer gemacht werden.

[NOTE]
Die Tatsache, dass ein Attribut *undefiniert* sein kann, bzw. dass es immer definiert sein muss, ist Teil des Modells.

[WARNING]
Undefiniert ist nicht einfach 0 oder sonst irgendein etwas besonderer Wert. Es ist ein eigenständiger Wert, der genau die Tatsache der Undefiniertheit wiedergibt.

In INTERLIS 2 schreibt man zum Beispiel:

[source]
----
CLASS Wetter =
  Temperatur: MANDATORY –50 .. 50 [oC];
  Windrichtung: (N, NE, E, SE, S, SW, W, NW) CIRCULAR;
  Windgeschwindigkeit: MANDATORY 0 .. 200 [kmh];
END Wetter;
----

Temperatur und Windgeschwindigkeit sind also obligatorisch (MANDATORY). Da die Windrichtung nicht obligatorisch verlangt wird, ist sie fakultativ. Der konkrete Wert darf damit undefiniert sein. In Erweiterungen ist es zulässig, aus fakultativen Attributen obligatorische zu machen. Obligatorische Attribute dürfen aber nicht zu fakultativen werden, da gemäss der Basisklasse der Wert «undefiniert» nicht erlaubt ist.

[#_6_6]
