[#_6_16]
=== Alles Gute kommt von oben – Vorhandene Modelle nutzen

Die Ilistaler haben es gut gemacht: Sie haben nicht alles neu erfunden, sondern vorhandene Modelle (Units, Ahland, Adressen, NatTour) genutzt. Aber ein bisschen gefrevelt haben sie doch. Beispielsweise ist die AhlandLinie sicher nicht typisch für das Ilistal und seine Berg­bahnen, sondern würde eigentlich in das landesweite Datenmodell von Ahland gehören. Auch WGS84Koord und die Tageszeit sind keine Ilistaler Spezialität.

Die Ilistaler haben sich insofern normal verhalten, als sie Dinge, die sie nicht anderswo gefunden haben, dem eigenen Modell beigefügt haben. Verständlich – aber nicht optimal.

[WARNING]
Fehlende oder falsche Definitionen auf allgemeinerer (höherer) Stufe sollte man nicht einfach hinnehmen, sondern in Zusammenarbeit mit den zuständigen Stellen ver­suchen, diese Modelle zu verbessern.

Es ist darum auch sinnvoll, dass grundlegende Typen auf verschiedenen Stufen vordefiniert werden. INTERLIS selbst stellt einige Basismodelle zur Verfügung. Andere Modelle werden durch Anwendergemeinschaften (z.B. Verbände) bereitgestellt. Nochmals andere sind sehr spezifisch, wie etwa dasjenige der Ilishornbahnen.

Abschnitt <<_3_3>> nennt einige Bezugsquellen für standardisierte Datenmodelle.

[#_6_17]
