[#_7_2]
=== Der Eurokurs schwankt von Tag zu Tag – Parameter und Funktionen

Für jede Billettart ist der Preis in der Landeswährung bekannt. Im Interesse der ausländischen Touristen soll er auch in Euro und US-Dollar bekannt gegeben werden. Man möchte aber nicht bei jeder Änderung der entsprechenden Währungskurse die Preise für alle Billettarten wieder neu eingeben. Sie sollen vielmehr aus der Landeswährung berechnet werden.

[source]
----
CLASS Billettart =
  Name: TEXT*100;
  Preis_TALER: 0.00 .. 5000.00 [Ahland.Taler];
  Preis_EUR: 0 .. 4000 [EUR] := TALERtoEUR (Preis_TALER);
  Preis_USD: 0 .. 4000 [USD] := TALERtoUSD (Preis_TALER);
END Billettart;
----

Immer wenn die Daten im System präsentiert oder als Daten für das WebSys bereitgestellt werden, werden die Euro- und Dollarpreise neu aus den Preisen in der Landeswährung be­rechnet. Die Berechnung erfolgt durch die beiden Funktionen TALERtoEUR bzw. TALER­toUSD. Aber woher soll das LiftSys im Speziellen, aber auch irgendein anderes System wissen, was diese Funktion leisten soll?

Die wichtigste Information besteht aus konzeptueller Sicht in der Tatsache, dass die beiden Fremdwährungspreise nicht als eigenständige Daten behandelt, sondern aus dem Talerpreis abgeleitet werden. Dafür reicht es aus, für eine bestimmte Funktion den Namen und ihre Parameter festzulegen.

[source]
----
FUNCTION TALERtoEUR (Taler: NUMERIC [Ahland.Taler]): NUMERIC [EUR]
  // Umrechnung in Euro //;
----

Die eigentliche Leistung der Funktion wird nur als Erläuterung zwischen // angegeben. Die Implementation bleibt Sache der Systeme. Solche Definitionen sollen auf wenige Basismodelle beschränkt sein, denn sie müssen mit den Herstellern der Systeme vereinbart werden. In INTERLIS 2 wird das Bestehen einer solchen Vereinbarung mit einem Kontrakt angemerkt. Funktionen können nur in solchen Modellen definiert werden, für die ein Kontrakt besteht.

[source]
----
CONTRACTED MODEL IlisTour AT http://www.interlis.ch/models/ahland
  VERSION "2008-01" =
  ...
END IlisTour;
----

Will man die Anzahl der Funktionen möglichst gering halten, müssen sie möglichst allgemein formuliert werden. Zum Beispiel könnte statt TALERToEUR eine allgemein verwendbare Funktion für die Division definiert werden.

[source]
----
FUNCTION Division (Dividend: NUMERIC, Divisor: NUMERIC): NUMERIC;
----

Allerdings vergibt man sich dabei auch wieder Kontrollmöglichkeiten, denn es besteht keine Gewissheit, dass die erste Angabe ein Betrag in der Landeswährung ist. Mit der nachfolgenden Form ist dies hingegen gewährleistet.

[source]
----
FUNCTION ToCurrency (Taler: NUMERIC [Ahland.Taler],
  Wechselkurs: NUMERIC [Ahland.Taler]):
  NUMERIC [MONEY];
----

Aber woher kommt der Wechselkurs? Man könnte für solche Fälle vorsehen, dass in den Systemen gewisse Werte wie der Euro- oder Dollarkurs als Parameter zur Verfügung stehen. Da auch damit wieder in die Systeme eingegriffen wird, ist auch die Definition von System-Parametern nur innerhalb von Kontrakten erlaubt.

[source]
----
PARAMETER
  EURKurs: 0.000 .. 5.000 [Ahland.Taler]; !! Preis eines Euro in Talern
  USDKurs: 0.000 .. 5.000 [Ahland.Taler];

CLASS Billettart =
  Name: Text * 100;
  Preis_TALER: 0.00 .. 5000.00 [Ahland.Taler];
  Preis_EUR: 0 .. 4000 [EUR] := ToCurrency (Preis_TALER, PARAMETER EURKurs);
  Preis_USD: 0 .. 4000 [USD] := ToCurrency (Preis_TALER, PARAMETER USDKurs);
END Billettart;
----

[#_7_3]
