[#_8_5]
=== Der Ponylift im «Val de la marmotte jaune» – Fremdsprachen beim Datentransfer

Gleich hinter dem Schwarzen Zahn liegt das «Val de la marmotte jaune». Sieht man einmal davon ab, dass hier französisch gesprochen wird, und dass die lokalen Murmeltiere ein ganz besonders intensiv gefärbtes Fell besitzen, lässt es sich kaum vom Ilistal unterscheiden.

Insbesondere erfreut auch hier ein Ponylift die Kinderherzen. Wie erfährt nun aber der nationale Tourismusverband, wie lange die Fahrt damit dauert? Schliesslich schlagen sich die im Datenmodell benutzten Bezeichnungen auch im Aufbau der Transferdateien nieder. Auf diese Weise kommt es in den Ilistaler Daten zu Zeilen wie ++<++Dauer++>++3++<++/Dauer++>++. Über­setzt man das Datenmodell in eine andere Sprache, ändert sich damit auch das entspre­chende Transferformat.

Wie geht also der nationale Tourismusverband zum Beispiel damit um, dass die Transfer­datei aus dem einen Tal die Zeile ++<++Dauer++>++3++<++/Dauer++>++ enthält, jene aus dem Nachbartal aber ++<++LapsTemps++>++3++<++/LapsTemps++>++?

Der Verband muss nun nicht für jede Landessprache eine separate Software einkaufen. IN­TERLIS sorgt dafür, dass trotz der Mehrsprachigkeit ein reibungsloser Transfer gewährleistet ist. Die einzige Bedingung ist, dass sich das Datenmodell beim Übersetzen nicht in seiner Struktur verändert hat. Wie in Abschnitt <<_6_18>> angesprochen wurde, steht ein Werkzeug (der so genannte INTERLIS-Compiler) zur Verfügung, mit dem ein übersetztes Datenmodell daraufhin überprüft werden kann, ob es strukturell gleich wie das Original ist.

