[#_8_3]
=== Einmal und immer wieder – Inkrementelle Nachlieferung

Ganze siebzehn Minuten auf dem Ponylift? Die armen Kinder sind da doch schon halb erfroren, bevor sie nur schon ihren ersten Stemmbogen gemacht haben! Eine derartige Bahn wird kaum eine Saison überleben; in vierzig Jahren interessiert sich für diese Daten bestimmt niemand mehr.

Schliesslich stellte sich heraus, dass der Ponylift doch nicht gigantisch überdimensioniert worden ist. Es hatte sich einfach jemand beim Erfassen vertippt: Nicht siebzehn, sondern nur eine einzige Minute dauert die Fahrt.

Natürlich war die Zahl schnell im LiftSys geändert. Musste man nun dem nationalen Verband die gesamten Daten gleich nochmals schicken?

[NOTE]
Dank der *inkrementellen Nachlieferung* müssen nach einer Änderung nicht alle Daten, sondern nur die Änderungen übermittelt werden. So müssen weniger Daten verschickt werden. Der Hauptnutzen liegt aber in der Dokumentation, was genau verändert wurde.

Mit dem LiftSys-Programm wurde eine Nachlieferung für den nationalen Verband erzeugt. Im Gegensatz zum Volltransfer enthielt die inkrementelle Nachlieferung nicht die Daten des ge­samten Ilistals, sondern nur die Daten von veränderten Objekten. Damit war sie viel kleiner und entsprechend leichter zu handhaben.

Nun macht es nicht immer Sinn, Daten inkrementell nachzuliefern. Der nationale Tourismus­verband bietet z.B. den Internet-Dienst, mit dem sich Touristen über die Abonnementspreise bei den verschiedenen Bergbahnen informieren können, nicht selbst an, sondern hat diese Aufgabe an eine Partnerfirma delegiert. Diese erhält dafür periodisch eine vollständige Kopie der Daten im INTERLIS 2-Format. Diese Daten werden durch ein Serverprogramm geladen, das die konkreten Anfragen beantwortet. Eine inkrementelle Nachlieferung würde nur die Anforderungen an dieses Serverprogramm steigern, ohne dass der Nutzen ersichtlich wäre.

[#_8_4]
