[#_8_2]
=== Klammern so spitz wie das Ilishorn – Transferregeln auf Basis XML

Was war denn überhaupt in dieser Datei enthalten? Man öffnete sie mit einem normalen Text-Editor.

.Der Ilistaler Ponylift als Teil des Volltransfers für die Ilistaler Daten. Der INTERLIS-Standard legt fest, wie genau eine solche Transferdatei für ein bestimmtes Datenmodell aufgebaut sein muss.
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
...
<BASKET BID="xAHTOUIHB01234567" TOPICS="IlisTour.Bergbahnen">
  <IlisTour.IhBBergbahnen.IhBBergbahn TID="xAHTOUIHB04231336">
    <Namen>
      <NatTour.Bezeichnung>
        <Name>Ponylift Ilisdorf</Name> <1>
        <Sprache>de</Sprache>
      </NatTour.Bezeichnung>
    </Namen>
    ...
    <LageBergstation>
      <P>
        <C1>8020.60</C1>
        <C2>13188.62</C2>
        <C3>1789.04</C3>
      </P>
    </LageBergstation>
    <Fahrzeit>
      <Ahland.ZeitdauerInMinuten>
        <Dauer>3</Dauer>
      </Ahland.ZeitdauerInMinuten>
    </Fahrzeit>
    <Art>Skilift</Art>
    ...
    <BildBergstation>
      http://www.ilishornbahnen.com/webcam?bahn=pony4
    </BildBergstation>
    ...
  </IlisTour.IhBBergbahnen.IhBBergbahn>
</BASKET>
...
----

Ziemlich viele spitze Klammern, ganz am Anfang etwas von XML (davon hatte man doch schon mal gehört!), wenn auch in Fragezeichen... Aha, hier war einmal etwas Einfacheres:

<1> Der Ponylift Ilisdorf.

Je nach Datenmodell ist die Transferdatei anders aufgebaut. Die Struktur ist aber natürlich nicht beliebig: Der INTERLIS-Standard schreibt mit präzisen Regeln vor, wie aus einem bestimmten Datenmodell das zugehörige XML-Format abzuleiten ist.

Etwas kompliziert, das Ganze – aber man konnte ja das LiftSys verwenden und musste daher all die Klammern gar nie von Hand eingeben. Immerhin war aber zum Beispiel auch ohne Spezialprogramm ersichtlich, dass die Fahrzeit mit dem Ponylift 3 Minuten dauert.

Der Informatiker erklärte, dass man mit diesen Daten auch noch in vierzig Jahren etwas anfangen können sollte. Auch dann noch, falls die Hersteller der ursprünglichen Programme bis dahin längstens Konkurs gegangen sein sollten, fünfzehn Mal eine neue Programmversion hätte installiert werden müssen, und auch wenn die Geräte bis dahin ganz anders aufgebaut wären. Die Behauptung erschien deswegen glaubhaft, weil es sogar ohne Dokumentation und rein auf dem Papier möglich (wenn auch mühselig) war, die Daten zu verstehen.

Aber was ist dieser komische Text «TID="xAHTOUIHB04231336"»? Er bezeichnet den Ponylift innerhalb der Transferdatei. Der Wert spielt nur für den Transfer eine Rolle: Diese Objekt-Identifikation steht überall dort, wo in der Transferdatei Bezug auf den Ponylift genommen wird. Beim Einrichten von LiftSys konnte angegeben werden, dass alle Identifikationen mit xAHTOUIHB beginnen sollen, ganz wie es der nationale Tourismusverband in seinem Schreiben gewünscht hatte.

Objektidentifikationen beginnen mit einem Ländercode gemäss ISO 3166 (ch für die Schweiz, fr für Frankreich, etc.) und sechs weiteren Zeichen, die von einer zuständigen, zentralen Stelle eindeutig vergeben werden. Die restlichen acht Zeichen vergibt das Computersystem automatisch.

Anhang D des INTERLIS-Referenzhandbuchs erklärt die Vergabe von Objektidentifkationen.

[#_8_3]
