[#_9_3]
=== Nagt der Zahn der Zeit am Ilishorn? – Lebenszyklen

Gute, d.h. sachgerechte, von der unmittelbaren Nutzung unabhängige Datenmodelle sind um so wichtiger, je langlebiger und allgemein brauchbarer die mit den Daten beschriebenen Sachverhalte sind. Bei Daten, die für einen privaten Zweck oder für ein zeitlich klar begrenztes Projekt, das mit einem bestimmten System abgewickelt wird, erhoben werden, ist das Datenmodell nicht so wichtig wie für Daten, die langlebig sind.

Daten, die die reale Welt beschreiben, sind aber in der Regel langlebig. Das Ilishorn selbst verändert sich nur in geologischen Zeiträumen. Aber selbst Häuser, Bahnen, Rechtsverhält­nisse haben Lebensdauern von einigen Jahren bzw. Jahrzehnten. Die Objekte in der Realität werden darum die Computersysteme, auf denen ihre Abbilder beschrieben sind, überdauern.

Damit auch die Abbilder der Realität, also die Datenobjekte die spezifischen Computer­systeme (Hardware und Software) überdauern können, braucht es eine klare Vorstellung über die Datenobjekte. Es braucht ein Datenmodell.

Dieses Datenmodell soll möglichst systemunabängig sein. Denn das nächste System hat voraussichtlich andere Fähigkeiten. Vielleicht können dann Sichten automatisch gebildet werden. In Anbetracht der relativ kurzen Lebensdauer von Softwarepaketen sollte man sich beim Strukturieren der Daten nicht zu stark davon leiten lassen, welche Funktionalität ein bestimmtes Softwarepaket zurzeit besitzt.

[#_9_4]
