[#_9_4]
=== Vor lauter Bäumen den Wald nicht mehr sehen – Detaillierungsgrad

Es steht ausser Frage, dass die reale Welt nicht so modelliert wird, dass die einzelnen Atome, aus denen die Realweltdinge bestehen, die Datenobjekte sind. Das wäre viel zu mühsam. Ein Gebäude soll sich auch nicht aus den einzelnen Backsteinen und Ziegeln zusammensetzen. Aber wann sprechen wir von einzelnen Bäumen, wann von einem Wald, ohne die einzelnen Bäume als Datenobjekte aufzuführen?

Natürlich hängt dies davon ab, was mit dem System erreicht werden soll. Wichtig dabei ist, dass es nicht nur darum geht, ein möglichst gutes Modell zu finden. Dieses muss auch umsetzbar sein. Ist das Modell verständlich? Ist es möglich, für die Datenerfassung und die Nachführung einen Dialog zu definieren, den die Menschen, die für die Arbeit vorgesehen sind, ohne Probleme bewältigen können?

Ein einfaches Modell, dessen verschiedene Objektklassen nicht allzu sehr miteinander ver­flochten sind, kann sich gerade in dieser Hinsicht positiv bemerkbar machen.

Je komplizierter ein Modell ist, desto wichtiger ist es, dass man dennoch eine Bedienungs­oberfläche findet, die intuitiv verständlich ist. In solchen Situationen ist es gefährlich, wenn ein Grundmodell so erweitert wird, dass nicht nur einzelne Attribute angefügt, sondern neue Beziehungen definiert werden. Die Gefahr, dass ein für das Grundmodell entworfener Bedienungsdialog seine Eleganz und Verständlichkeit verliert, ist gross.

Einmal mehr gilt: «So einfach wie möglich, so komplex wie nötig». Die gute Umsetzung dieses Grundsatzes ist aber bekanntlich nicht einfach.

[#_9_5]
