[#_9_1]
=== Viele Wege führen aufs Ilishorn – Das richtige Modell gibt es nicht

Die Ilistaler sind sich natürlich bewusst, dass ihr Datenmodell nicht jeder Kritik standhält. Da es das Ilistal in der Realität gar nicht gibt, wurde auch darauf verzichtet, das Modell unter verschiedenen Gesichtspunkten immer wieder zu hinterfragen. Schliesslich ging es primär darum, die verschiedenen Aspekte der Modellierung und die entsprechenden Instrumente vorzustellen.

Bei jedem Modell stellt sich aber die Frage: Ist das Modell richtig? Oder fragt man vielleicht besser: Ist das Modell gut?

Sicher greift die Haltung zu kurz, die jedes Modell als richtig oder gut bezeichnet, das die Anforderungen der Beschreibungssprache rein formal erfüllt. Nur weil ein Modell vom INTER­LIS-Compiler akzeptiert wird, ist es sachlich noch nicht gut.

Die Haltung entsprechend dem Sprichwort «Viele Wege führen nach Rom» – oder eben aufs Ilishorn – kommt der Sache schon näher. Es ist offensichtlich, dass es verschiedene Möglichkeit gibt, einen bestimmten Sachverhalt zu modellieren. Nicht alle möglichen Modelle sind aber gleich gut. Schliesslich gibt es auch breite, schmale, holprige, steile, befahrbare, aussichtsreiche Wege aufs Ilishorn. Nicht jeden Tag wählt man den gleichen Weg als den besten aus. Die Bedürfnisse und damit die Beurteilungskriterien sind schliesslich auch nicht immer die gleichen.

In den nächsten Abschnitten werden deshalb verschiedene Beurteilungskriterien beleuchtet, die für die Datenmodellierung von einiger Bedeutung sind.

[#_9_2]
