[#_9_2]
=== Das Ilishorn aus verschiedenen Blickwinkeln – Originaldaten und Sichten

Orientiert man sich bei der Datenmodellierung am unmittelbaren Bedürfnis, besteht die Gefahr, dass die Daten ungeeignet erfasst werden. So ist es z.B. ungeeignet, bei einer Person das Alter als Attribut vorzusehen. Dieses ändert schliesslich dauernd. Besser ist es, das Geburtsdatum als Attribut festzulegen und das Alter mittels einer Sicht aus dem Geburts­datum und dem aktuellen Datum abzuleiten (vgl. Abschnitt <<_6_17_2>>).

Wenn das Datenmodell so gebildet ist, dass es der eigentlichen Sache und nicht einer bestimmten Betrachtungsweise entspricht, können wir für die konkreten Nutzungen flexibel reagieren und sie aus den Originaldaten ableiten. Die Daten enthalten dann eben das Ilishorn und nicht den Blick von Ilisdorf oder Ilisbad aus. Diese und beliebige andere Per­spektiven können als Sichten aus den Daten abgeleitet werden.

Manchmal ist die Ableitung der gewünschten Sichten aus «ideal» modellierten Daten aber recht anspruchsvoll. Insbesondere Sichten, die Bildungsgesetze mit geometrischen Berechnungen enthalten, sind nicht immer einfach realisierbar. Der Entscheid, wann von der Tugend abgewichen werden kann und das Datenmodell an der Sicht ausgerichtet wird, ist nicht immer einfach und hängt in der Regel von weiteren Beurteilungskriterien ab. Auch wenn man sich für ein Modell entscheidet, das nicht die eigentlichen Daten sondern eine Sicht auf sie beschreibt, lohnt es sich aber, zu überlegen, welches das «schöne» Modell wäre. Es fällt dann leichter, zu gegebener Zeit auf dieses Modell zurückzukommen und damit die Nachteile des sichtorientierten Modells zu überwinden.

Der Hauptnachteil eines sichtorientierten Modells zeigt sich in der Erfassung und vor allem in der Nachführung der Daten. Führt man z.B. für jeden Gebäudeeingang den Strassennamen, die Hausnummer, die Postleitzahl und die Ortschaft als direktes Attribut, besteht die Gefahr, dass sich Fehler, z.B. unterschiedliche Schreibweisen, einschleichen. Zudem ist der Erfassungsaufwand wesentlich grösser. Noch schlimmer wird es in der Nachführung, wenn z.B. die neue Siedlung Ilismühle als Ortschaft mit eigener Postleitzahl eingeführt und der hintere Teil von Ilisdorf dieser neuen Ortschaft zugeordnet wird. Alle betroffenen Gebäudeeingänge mutieren? Besser wäre es, man könnte einfach die neue Ortschaft samt ihrem Gültigkeitsbereich einführen und den Gültigkeitsbereich von Ilisdorf entsprechend anpassen.

Mit guten Modellen erreicht man, dass ein veränderter Sachverhalt in der Realität zu genau einer Änderung in den Daten führt. Alles Weitere kann mittels Sichten abgeleitet werden.

[#_9_3]
