[#_10_5]
=== V. Unterschiedliche Auswirkungen auf die beteiligten Systeme

Im Rahmen der Gesamtlösung wurden verschiedene Computersysteme eingesetzt. Ins­besondere konnten die bisherigen Systeme weiterhin genutzt werden. UML und INTERLIS schreiben nämlich nicht vor, wie die Systeme aufgebaut sein sollen, sondern nur, wie die Daten letztlich geliefert werden, damit sie der konzeptuellen Vorstellung entsprechen.

Das System des Bauamtes war direkt in der Lage, die zu transferierenden Daten zu erstellen und empfangene Daten zu lesen. Beim System der Ilishornbahnen wurde ein Konverter eingesetzt, also ein Programm, welches die system-spezifischen Daten in ein neutrales Transferformat umsetzte. Bei den kleinen Erfassungssystemen an den Talstationen konnte mit einfachsten Programmen dafür gesorgt werden, dass auf Grund der Messung jeweils ein korrekter Datensatz als inkrementelle Nachlieferung an die Zentrale gesendet wird.

Interessant ist auch ein Blick auf das System des nationalen Verbandes. Diesem konnten nämlich Dateien geschickt werden, die auch die durch uns definierten Zusätze enthalten. Dank dem Prinzip des polymorphen Lesens störte das überhaupt nicht.

Ein Grund, dass dies alles möglich war, lag wohl auch daran, dass INTERLIS 2 auf dem internationalen Standard der _Extensible Markup Language_ (XML) aufbaut.

[#_10_6]
