[#_10_2]
=== II. Sachen, Abbilder und der Zahn der Zeit

Der Beizug eines weiteren Fachmanns hat sich gelohnt. Die ersten Gespräche waren dann zwar etwas überraschend. Technische Schlagworte fehlten oder wurden wieder vom Tisch gefegt. Dafür folgte eine gründliche Auseinandersetzung mit der Sache.

Erste Erkenntnis: Sache ist nicht, was im Computer drinnen steckt oder gar, was er als Bilder, Tabellen und andere Präsentationen ausspuckt, sondern was in der Realität existiert und passiert.

Das, was im Computer drin ist, kann mit einem Holzmodell oder einem Sandkasten verglichen werden. Die Fotos, die wir davon aus verschiedenen Richtungen und mit verschiedener Beleuchtung machen, können mit dem Bildschirm oder mit Ausdrucken verglichen werden. Und eines ist ja auch bei Holzmodellen oder Sandkasten offensichtlich: Die Realität zum ersten Mal abzubilden ist eine Riesenarbeit. Bis da all die Häuser, Strassen, Bahnen, die in der Realität existieren, auch im Abbild in vereinfachter Form aufgebaut sind! Noch schlimmer als die Ersterfassung ist dann die Nachführung: Schon nach kurzer Zeit müssen Änderungen gemacht werden, um das Abbild aktuell zu halten. Und der Zahn der Zeit nagt an den Sand- und Gipsstrukturen. Da hat man es mit dem Computer schon besser! Natürlich muss auch hier nachgetragen werden, wenn sich die Realität ändert, aber wenigstens veralten die verbleibenden Informationen nicht.

Wirklich? Nein, wirklich nicht so schnell wie im Sandkasten. Aber nach wenigen Jahren möchten wir wieder einen neuen, leistungsfähigeren Computer kaufen, und nach nochmals etwas längerer Zeit ist auch die Software für die Bearbeitung nicht das Beste, was es gibt. Man möchte neue Programme einsetzen. Und wie bringt man jetzt das elektronische Abbild der Realität vom alten System aufs Neue? Wie bringt man quasi den Sand vom alten in den neuen Sandkasten, ohne dass er zwischen den Händen zerrieselt und das Werk neu aufge­baut werden muss?

[#_10_3]
