[#_10_4]
=== IV. Systemunabhängiger Datentransfer

Ähnlich wie bei der Beschreibung der Struktur der Daten verhält es sich mit den Daten selbst. Es braucht also nicht nur eine Norm für die Datenbeschreibung, sondern auch eine Norm für den Datentransfer. Beim Übertragen der Daten von einem System auf ein anderes wird quasi Esperanto gesprochen, innerhalb der einzelnen Systeme dagegen die jeweilige Muttersprache.

Nachdem man sich so intensiv mit dem Aufbau der Daten auseinandergesetzt hat, möchte man sich eigentlich nicht mehr um diese Details kümmern. Hier hat sich der Einsatz von INTERLIS gleich nochmals gelohnt: Mit der Beschreibung der Datenstruktur ist nämlich auch gleich festgelegt, wie die zugehörigen Daten transferiert werden.

Wichtig ist dabei, dass die Datenbeschreibung nicht nur von Menschen gelesen und verstanden werden kann. Wegen der formalen Sprachdefinition kann sie auch durch Com­puterprogramme gelesen werden. Aufgrund von Datenbeschreibung und Transferregeln ist klar, wie in der Folge der Datentransfer aufgebaut sein muss.

[#_10_5]
