[#_11]
== Register

Verweise auf das ausführliche Beispiel in <<_4>> sind in _Schrägschrift_ gesetzt.

A

Abstrakt _35_, 46

Adresse 29, 116

auf dem Internet _Siehe_ URI

Aggregation 97

bei Beziehungen _35_, 79

bei Sichten 97

Allgemeiner Fall _Siehe_ Vererbung

Amtliche Vermessung 29, 116

Area _Siehe_ Gebietseinteilung

Arten _35_, 53

Assoziation _35_, 79

Attribut 13

bei Beziehungen 80

fakultativ 57

obligatorisch 57

Attributtyp _Siehe_ Datentyp

Aufbau auf Vorhandenem 17

Aufschlüsselung 97

Aufzählung _35_, 54

abgeschlossen 56

geordnet _40_, 55

strukturiert 56

und Vererbung _37_, 54

zyklisch _40_, 56

Ausprägung 12

B

Basisklasse _Siehe_ Vererbung

Behälter 92, 107

Beschreibung _Siehe_ Datenmodell

Beziehung 11, _35_, 78

abgeleitet _38_, 85

Aggregation 79

Assoziation 79

Beziehungsklasse _36_

geordnet 82

Komposition _39_, 79

mehrgliedrig _36_, 81

Stärke 79, 85

themenübergreifend 92

und Vererbung 83

Bézierkurve 103

Bezugssystem

von Koordinaten 65

von Zeitpunkten 77

Bildungsgesetz _Siehe_ Sicht

Booch 27

C

Codierung 24

Compiler 30, 99, 109

D

Datenaustausch _Siehe_ Transfer

Datenbeschreibung 27

Datenmodell 11, 115

Darstellung 27

mehrsprachig 99

standardisiert 29, 93

Datensatz 12

Datentyp 14, _32_, 58

geometrisch 65

numerisch _36_, 52

strukturiert 76

E

Eigenschaft 13

abstrakt 53

erben _Siehe_ Vererbung

Eindeutigkeit _34_, 88, 108

Einheit _32_, 52

Einschränkung _Siehe_ Vererbung

Ellipsoid 59

Ellipsoidhöhe 62

Enklave 68

Entitätsmenge 11

Erben _Siehe_ Vererbung

Erweiterung _Siehe_ Vererbung

Exemplar 12

Existenzerfordernis 90

F

Feld 13

Fläche 67

Fliesskommazahl 51

Föderalismus 28, 47, 117

Funktion _37_, 102

G

Ganzzahl 51

Gebietseinteilung _40_, 68

Genauigkeit

von Linien 66, 104

von numerischen Werten 52

Geoid 62

Geradenstück 66, 103

GML 30

Grafik 25

Grössenordnung 51

H

Hilfspunkt 104

Höhe 62

I

Identifikation

beim Transfer 106, 108

mit Attributen 88

Vergabe 107

Inkrementelle Nachlieferung 16

Inspection 97

Integer 51

Internet-Adresse _Siehe_ URI

ISO 19100 29

ISO 3166 107

J

Join 95

K

Kardinalität 13

Klassendiagramm 11

Klothoide 103

Kolonne 13

Komposition _39_, 79

Konsistenzbedingung _38_, 86

für Stützpunkte 91

und Vererbung 91

Kontrakt 102

Koordinaten _32_, _35_, 58

im Raum _32_, 62

zum Etablieren von Beziehungen 85

Koordinatensystem 59

Kreisbogen 66, 104

L

Leitungsnetz 29

Linie 65

Aufbau 66, 72, 103

gerichtet 67

im Raum 69

speziell geformt 103

M

Mehrfachvererbung 49

Mehrsprachigkeit 72

bei Objekteigenschaften _34_

beim Transfer 109

von Datenmodellen 99

Metadaten 60

Modell _Siehe_ Datenmodell

Modellbasierter Ansatz 30

Modul 17

N

Nachführung 115

Nachhaltigkeit 106

Nachlieferung 16

Numerischer Datentyp _36_, 52

O

Oberklasse _Siehe_ Vererbung

Object Management Group 30

Objekt 12

Objektidentifikation _Siehe_ Identifikation

Objektkatalog 11

Objektklasse 11

OMG 30

OMT 27

OOSE 27

P

Package 17

Paket 17

Parameter 102

Plausibilität 87

Polymorphes Lesen 24, 107, 117

Polymorphismus 47

beim Transfer 24, 107, 117

Projektion

bei Sichten 95

von Koordinaten 59

Proxy-Objekt 107

R

Radius 104

Real (Fliesskommazahl) 51

Replikat 107

Richtung 64

Rolle _35_, 78

S

Schema _Siehe_ Datenmodell

Schwerehöhe 62

Segment 66

Sicht 25, _38_, 93

Aufschlüsselung 97

Bildungsgesetz 94

schrittweiser Aufbau 97

und Vererbung 98

Verbindung 95

Vereinigung 97

Zusammenfassung 97

Spezialfall _Siehe_ Vererbung

Spline 103

Stellvertreter 107

Struktur 71

als Aufschlüsselung 97

als Zusammenfassung 97

und Vererbung 71

Subklasse _Siehe_ Vererbung

Superklasse _Siehe_ Vererbung

Systemneutralität 101

T

Tabelle 11

Text _34_, 57

Thema 19, 91

Topic _Siehe_ Thema

Transfer 16, 105

an übergeordnete Stellen 24

der Beispieldaten _41_

Format 22

Identifikation 106

inkrementell 107, 108

mit Konversionsprogramm 24, 101

modellbasiert 22, 117

polymorphes Lesen 107

systemspezifisch 23

systemunabhängig 117

und Mehrsprachigkeit 109

vollständig 16, 108

von Linien 104

Tupel 12

Typ _Siehe_ Datentyp

Ü

Überlappung

bei Flächen _Siehe_ Gebietseinteilung

bei Linien 66

U

Umlaute 24

Undefiniertheit 57

Unified Modeling Language 27, 116

UML-Editor 30

Union 97

Unteraufzählung 56

Unterklasse _Siehe_ Vererbung

URI _38_, 57

V

Verbindung 95

Vereinigung 97

Vererbung

im Grossen 20, 47

mehrfach 49

Prinzipien 43

übertrieben detailliert 44

von Aufzählungen _37_, 55

von Beziehungen 83

von Konsistenzbedingungen 91

von numerischen Wertebereichen 52

von Sichten 98

von Strukturen 71

von Themen 20, 47

Verknüpfung _Siehe_ Beziehung

Vermessung 29, 116

Verträglichkeit 47

Verweis _Siehe_ Beziehung

View _Siehe_ Sicht

Volltransfer 16

W

Währung 52, 102

Wertebereich 14, _32_, 58

geometrisch 65

numerisch _36_, 52

strukturiert 76

Winkel 64

X

XML 29, 105, 117

Z

Zeichencodierung 24

Zeichenkette _34_, 57

Zeichenvorrat 24

Zeiger _Siehe_ Beziehung

Zeitdauer _33_, _35_, 74

Zeitpunkt _33_, 77

Zusammenfassung 97
