[#_1]
== Une fiction au service de la réalité

Qui n'a jamais ressenti cette impression de découragement: ce n'est pas la peine, je n'y comprends rien! Et ce jargon impénétrable pour couronner le tout! Ne pouvait-on pas expliquer les choses plus simplement?

C'est le pari que nous allons tenter de relever avec « La modélisation de données à référence spatiale », en adoptant un point de vue de néophyte (pour ne pas dire de béotien…) et en incluant nos explications au sein d'une fable, l'histoire du Val d'IIi et de son modèle de données. Le Val d'Ili est imaginaire, c'est donc nulle part. Mais c'est aussi partout, en ce sens que notre histoire fourmille de situations, de questions et de problèmes auxquels nous avons déjà été confrontés et que certains ne connaissent que trop bien. Dans ce document, le pays du Val d'Ili sera la Béotie (dont les habitants sont les béotiens). Les allers-retours entre le monde imaginaire du Val d'Ili et celui de réalités théoriques et pratiques plus austères sont fréquents et concernent des niveaux d'intérêt et de connaissances différents:

* *Aperçu général* – La vue générale brossée au <<_2>> introduit les principaux éléments de la modélisation de données et du transfert de données basé sur un modèle.
* *Méthodes de modélisation* – Le <<_3>> apporte un éclairage sur différentes méthodes de modélisation connues, indique le positionnement d'UML et d'INTERLIS et précise où il est possible d'obtenir des informations supplémentaires.
* *Exemple du Val d'Ili* – Il est exposé en détail au <<_4>>. Les modélisations réalisées touchent différents aspects propres au domaine du tourisme et les solutions définies ne prétendent aucunement à la perfection. Notre objectif essentiel est de mettre des principes de modélisation en lumière à l'aide d'exemples. Des renvois à des explications complémentaires fournies aux chapitres 5 à 8 facilitent en outre l'accès aux considérations théoriques. Ce chapitre peut constituer une entrée en matière idéale pour celles et ceux disposant déjà de quelques connaissances concernant la modélisation de données et le transfert basé sur un modèle.
* *Examen approfondi de l'exemple* – L'héritage jouant un rôle central dans la méthode de modélisation présentée, le <<_5>> y est largement consacré. Les chapitres suivants traitent de la modélisation de données en général (<<_6>>), de son influence sur les logiciels mis en œuvre (<<_7>>) et du transfert de données (<<_8>>). Si le lecteur estime que les chapitres 5 à 8 entrent dans des considérations trop techniques à son goût, il peut se simplifier l'existence et les sauter. Des consultations ponctuelles sont également possibles dans ces chapitres, raison pour laquelle les titres des sous-chapitres comprennent toujours un volet relatif à l'histoire du Val d'Ili et une expression technique.
* *Considérations fondamentales* – Le <<_9>> aborde quelques aspects fondamentaux à respecter durant la modélisation de sorte que sa lecture devrait également intéresser un public moins friand de détails techniques.
* *Rapport final pour les administrations et le management* – Le <<_10>> récapitule les points principaux (à l'attention des administrations du Val d'Ili, du management des remontées mécaniques et des organisations touristiques). Le manager hyperactif et pressé de notre monde bien réel passera directement à ce chapitre, de façon à se faire une idée globale des problèmes qui se posent et des moyens à disposition pour les résoudre.

