[#_3_1]
=== Description sous forme graphique : Unified Modeling Language UML

Un diagramme se prête particulièrement bien à l'obtention d'une vue d'ensemble sur un modèle, pour soi-même comme pour des tiers, raison pour laquelle on recourt à des notations graphiques en informatique depuis le milieu des années 1970 afin de visualiser des modèles. De nombreuses années s'écoulèrent toutefois avant que l'on finisse par s'accorder sur un mode de représentation unifié, si bien que des dizaines de notations différentes ont simultanément été en usage. Au début des années 1990, trois méthodes parvinrent à s'imposer : Booch, OMT et OOSE. Leurs concepteurs, que l'on appelait les « tres Amigos » convinrent en 1995/96 d'un langage de modélisation unique et unifié, l'_UML_ _(Unified Modeling Language)_. Depuis 1997, UML est géré comme une norme par un consortium d'industriels, intitulé l'_Object Management Group_.

Le langage UML sait faire preuve de souplesse comme de polyvalence. Quiconque est familiarisé avec sa notation est capable de déchiffrer d'un coup d'oeil des modèles dans les domaines d'application les plus divers. Ce langage n'est du reste pas uniquement adapté à la modélisation de données (au moyen des diagrammes de classes présentés dans le cadre de ce document) mais englobe également des éléments permettant de couvrir d'autres aspects d'un système, par exemple sa subdivision en composants ou des scénarios d'utilisation.

La faculté d'adaptation d'UML constitue une clé importante de son succès : l'infrastructure mise à disposition par le langage est suffisante pour bon nombre d'applications, mais il est possible à tout moment d'adapter le langage à ses propres besoins par l'intermédiaire de mécanismes d'extension clairement définis et également standardisés.

Si un langage visuel tel qu'UML possède d'indéniables avantages, il n'en constitue pas pour autant la panacée. Dès lors qu'il s'agit de définir les détails d'un modèle complexe et de grande ampleur, un diagramme perd rapidement de sa clarté et pire, peut semer la confusion. Une représentation graphique se révèle par ailleurs assez peu pratique pour certaines tâches, par exemple pour configurer un système informatique. Dans certains cas, une forme textuelle semble donc plus appropriée : les modèles sont transcrits sous forme de texte dans un langage normalisé et peuvent de la sorte être compris par l'homme comme par la machine. Bien évidemment, l'image peut continuer à être utilisée pour obtenir une vue d'ensemble sommaire. Des propositions de notation purement textuelle d'UML sont actuellement en discussion, aucune norme correspondante n'ayant cependant été publiée à ce jour.

[#_3_2]
