[#_3_2]
=== Description sous forme textuelle : INTERLIS

En Suisse, il a été reconnu voilà bien longtemps qu'une méthode fondée sur un modèle comportait des avantages considérables. C'est ainsi que le langage de modélisation textuel INTERLIS a été développé en 1991 dans le cadre de la mensuration officielle. La fin des années 1990 a vu l'élaboration d'INTERLIS 2, étendant et modernisant la première version. Une demi-douzaine de spécialistes issus des milieux de la recherche, de l'administration et de l'industrie a scrupuleusement veillé à ce que le langage respecte les exigences concrètes de la pratique. Une grande valeur a par ailleurs été attachée au fait que certaines particularités résultant des applications elles-mêmes soient prises en compte :

* Avec INTERLIS, les modèles de données peuvent être décrits avec précision et à un haut degré de spécification. Un modèle INTERLIS peut ainsi faire partie intégrante d'un appel d'offres, d'un contrat ou d'une ordonnance et il est également envisageable de configurer un logiciel à l'aide d'un modèle INTERLIS.
* INTERLIS englobe non seulement un langage de modélisation de données, mais également une méthode grâce à laquelle le format de transfert utilisé pour l'échange des données modélisées peut être déduit du modèle. Cette propriété revêt une importance particulière en raison du volume de travail conséquent qu'implique la saisie de données géographiques et de la valeur très élevée qui y est attachée. La durée de validité de telles données étant par ailleurs de quelques décennies, elle dépasse très largement celle des systèmes informatiques, obsolètes au bout de quelques années à peine. Les données ainsi chèrement acquises ne peuvent être protégées que si elles sont conservées sous une forme totalement indépendante de tout logiciel.
* Il va de soi qu'INTERLIS peut être utilisé pour des applications dénuées de toute référence géographique, mais ce langage est particulièrement bien adapté à des données à référence spatiale. La prise en compte de la géométrie est ancrée au cœur même du langage. Des mesures ont par ailleurs été prises visant à contrôler automatiquement la qualité et la plausibilité des données livrées.
* Les modèles de données INTERLIS sont clairement structurés : un modèle est subdivisé en thèmes comprenant à leur tour des classes d'objets. La description d'une classe d'objets recourt aux propriétés de ces objets de même qu'à des règles d'intégrité et à des conditions de plausibilité. Il est possible, au niveau du modèle comme à celui des thèmes, de déclarer des éléments utilisables en toutes circonstances (exemple : des unités, des domaines de valeurs, des structures auxiliaires).
* La structure fédérale de la Suisse avec ses 26 cantons et demi-cantons, eux-mêmes subdivisés en unités administratives plus petites, impose des exigences particulières à un langage de modélisation. INTERLIS 2 permet à l'ensemble des intervenants de partager un noyau de modèle commun qu'ils peuvent étendre ou affiner au gré des besoins qui leur sont propres. L'absence de tout problème durant l'échange des données reste ainsi garantie même si des modèles localement différents sont utilisés. INTERLIS est par ailleurs conçu pour permettre la rédaction des modèles dans des langues différentes. Ainsi, la langue usuelle dans chacune des régions linguistiques du pays pourra servir à l'élaboration des modèles.

INTERLIS et UML se complètent mutuellement : les diagrammes UML, rapidement tracés, se prêtent idéalement à l'obtention d'une vue d'ensemble sommaire. INTERLIS permet quant à lui une plus grande précision dans le détail, sans pour autant recourir à une procédure excessivement complexe, et tient en outre compte des exigences propres aux pratiques fédérales en matière de géodonnées. Des outils ont été développés pour convertir automatiquement un diagramme de classe UML en description textuelle INTERLIS. Et réciproquement, la représentation d'un modèle INTERLIS en notation UML peut également s'effectuer automatiquement.

[#_3_3]
