[#_5_5]
=== Les détails ne nous intéressent pas – Considérer les particularités de façon plus globale

Lorsque quelqu'un se renseigne de manière générale sur le réseau ferré du pays, peu lui importe de savoir si une ligne donnée est un tramway, une remontée mécanique ou quoi que ce soit d'autre. Et il ne se préoccupe pas non plus de connaître les détails techniques du système au cas où la ligne serait à crémaillère. Non, le nom (saisi pour chacune des lignes, conformément au modèle de données) lui suffit amplement.

[NOTE]
====
Des exemplaires d'une sous-classe peuvent toujours être considérés sur un plan plus général, au sens d'une sur-classe.

_Le terme utilisé pour désigner ce principe est le polymorphisme._
====

Cela ne fonctionne toutefois qu'à une condition :

[NOTE]
Toute extension doit être *compatible* avec sa définition de base. Compatible, cela signifie que toute valeur acceptable par la définition étendue respecte également les règles du type de base (texte, énumération, valeur numérique, coordonnées, etc.).

[#_5_6]
