[#_5_3]
=== Et ça existe vraiment ? – Classes abstraites

Certaines classes ne sont rien d'autre que des auxiliaires théoriques, en ce sens qu'il n'en existe aucun exemplaire réel. Prenons un exemple : aucun être vivant sur cette planète ne fait simplement partie de la catégorie des êtres vivants, tous entrent simultanément dans l'une ou l'autre de ses sous-catégories. De la même manière, un modèle de données pourrait définir qu'il n'existe pas de ligne / remontée à proprement parler mais que toute ligne / remontée doit faire partie d'une sous-classe, qu'il s'agisse d'une remontée mécanique, d'une ligne de tramway ou de tout autre type.

[NOTE]
Une classe est déclarée comme étant *abstraite* si aucun objet concret ne peut lui être affecté.

Il est fréquent que toutes les sur-classes d'un modèle de données soient de type abstrait et que seules les sous-classes spécialisées des niveaux inférieurs soient concrètes.

[source]
----
CLASS Ligne_Remontee (ABSTRACT) =
  Nom: TEXT*100;
END Ligne_Remontee;

CLASS RemonteeMecanique EXTENDS Ligne_Remontee =
  PosStationInf: CoordNational;
  PosStationSup: CoordNational;
END RemonteeMecanique;

CLASS LigneTramway EXTENDS Ligne_Remontee =
END LigneTramway;
----

Figure 28 : La classe des lignes / remontées comme classe abstraite : s'il ne peut y avoir d'objet se contentant d'être une ligne / remontée sans être simultanément une remontée mécanique ou une ligne de tramway, par exemple, alors le nom de la classe correspondante figure en italique sur le diagramme. A droite, le même modèle est décrit en notation INTERLIS.

[#_5_4]
