[#_6_5]
=== Calme plat – Attributs facultatifs et obligatoires

Les données actuelles relatives à l'exploitation intègrent également des informations météorologiques telles que la température ou la vitesse du vent. L'indication de la direction du vent ne présente aucun intérêt en cas de calme plat. Les autres informations sont à fournir en toutes circonstances.

[NOTE]
Le fait qu'un attribut puisse être *indéfini* ou qu'il doive être défini en toutes circonstances est une composante du modèle.

[WARNING]
Indéfini ne signifie pas simplement égal à 0 ou à toute autre valeur particulière. Une valeur spécifique sert à décrire cette situation.

Dans INTERLIS 2, on écrira par exemple :

[#listing-06_05-01]
.link:#listing-06_05-01[Listing 06.05-01]
[source]
----
CLASS Meteo =
  Temperature: MANDATORY –50 .. 50 [oC];
  DirectionVent: (N, NE, E, SE, S, SW, W, NW) CIRCULAR;
  VitesseVent: MANDATORY 0 .. 200 [kmh];
END Meteo;
----

La température et la vitesse du vent sont donc obligatoires (MANDATORY). La direction du vent n'étant pas obligatoirement requise, elle est donc facultative. La valeur concrète de ce paramètre peut donc être indéfinie. Il est permis, dans des extensions, de rendre obligatoires des attributs facultatifs. En revanche, des attributs obligatoires ne peuvent pas devenir facultatifs puisque la valeur « indéfinie » n'est pas permise dans la classe de base.

[#_6_6]
