[#_6_10]
=== Comment le vent souffle-t-il ? – Structures

[#_6_10_1]
==== Propriétés multiples

Peu avant la Crête d'Ili, les personnes assises sur le télésiège se mettent soudain à se couvrir les oreilles et à remonter leur col : le vent est vraiment cinglant ici. Dans le cas du vent, il importe non seulement de connaître sa vitesse mais également la direction dans laquelle il souffle. Si l'on se contente de réunir ces deux propriétés avec d'autres attributs dans le cadre d'une description de classe, elles perdent de leur vigueur.

[#listing-06_10-01]
.link:#listing-06_10-01[Listing 06.10-01]
[source]
----
CLASS Temps =
  Temperature: MANDATORY -50 .. 50 [oC];
  DirectionVent: MANDATORY (N, NE, E, SE, S, SW, W, NW) CIRCULAR;
  VitesseVent: MANDATORY 0 .. 200 [kmh];
END Temps;
----

En conséquence, lorsqu'une situation n'est pas décrite par une seule valeur mais par plusieurs, il est judicieux de définir une structure (InfoVent) englobant ces propriétés (direction du vent, vitesse du vent).

[#listing-06_10-02]
.link:#listing-06_10-02[Listing 06.10-02]
[source]
----
STRUCTURE InfoVent =
  DirectionVent: MANDATORY (N, NE, E, SE, S, SW, W, NW) CIRCULAR;
  VitesseVent: MANDATORY 0 .. 200 [kmh];
END InfoVent;
----

Notions apparentées aux structures : types de données, types de données structurés, ...

Cette structure peut être utilisée partout où un avis concernant le vent est émis.

[#listing-06_10-03]
.link:#listing-06_10-03[Listing 06.10-03]
[source]
----
CLASS Temps =
  Temperature: MANDATORY -50 .. 50 [oC];
  Vent: InfoVent;
END Temps;

CLASS Anemometre =
  Lieu: MANDATORY CoordNational;
  Vent: InfoVent;
END Anemometre;
----

[#_6_10_2]
==== Plusieurs éléments structurés

L'anémomètre de la Crête d'ili est un peu particulier : il n'indique pas uniquement la valeur actuelle mais présente aussi les six dernières valeurs mesurées. Les gens n'en sont pas réchauffés pour autant mais sont généralement surpris de constater la vitesse à laquelle les changements peuvent se produire.

[#listing-06_10-04]
.link:#listing-06_10-04[Listing 06.10-04]
[source]
----
CLASS Anemometre =
  Lieu: MANDATORY CoordNational;
  Vent: LIST {6} OF InfoVent;
END Anemometre;
----

L'attribut Vent englobe donc six éléments (valeurs de mesure incluant à chaque fois la direction et la vitesse du vent). Il est indiqué par LIST OF que l'ordre de succession a son importance (par exemple la valeur la plus récente en tête). Si l'ordre de succession était sans importance, on écrirait BAG OF. Le nombre d'éléments mimal et maximal qu'il est possible d'énumérer peut être précisé, comme dans le cas des relations.

[#_6_10_3]
==== Structures et classes

Du point de vue formel, les structures et les classes (d'objets) sont très similaires. Des différences considérables existent cependant en pratique. Une classe (société de remontées mécaniques, anémomètre) décrit la manière dont les objets sont constitués tandis qu'une structure décrit la manière dont des propriétés plus complexes d'objets (InfoVent) sont constituées. Une structure sert donc au même but qu'un domaine de valeurs : décrire la manière dont un attribut est constitué. Parfois, une structure n'est requise que lorsque la propriété considérée doit être décrite de façon plus détaillée alors que la seule indication d'un domaine de valeurs suffit dans le cas d'une description plus simple (cf. § <<_6_12>>).

Les instances de classes sont des objets autonomes (Remontées mécaniques de la Dent d'Ili, anémomètre de la Crête d'Ili). Les instances de structures sont des éléments structurés (vent de 180 km/h soufflant du NE). La valeur d'un attribut de structure peut se limiter à un seul élément structuré ou en englober tout un ensemble (BAG OF, LIST OF).

[NOTE]
Une *structure* est très proche d'une classe d'objets sur le plan formel et d'un domaine de valeurs sur le plan pratique. Les exemplaires correspondants, les *éléments structurés*, ne possèdent cependant pas d'identité propre, ce sont des valeurs d'attributs d'un objet.

Les objets peuvent être en relation les uns avec les autres (cf. § <<_6_13>>). Les valeurs (de domaines de valeurs ou de structures) ne le peuvent pas. Il est toutefois possible de comparer entre elles des valeurs semblables d'objets différents (et de classes différentes) et les mettre ainsi en relation (cf. § <<_6_17>>). On pourrait donc comparer le prix du forfait du randonneur avec celui du steak du bûcheron que l'on mangerait de bon coeur au restaurant de la Crête d'Ili le jour de cette randonnée pédestre. Il n'en existe pas pour autant de relation entre le forfait du randonneur et le steak du bûcheron.

Il est nécessaire, dans certains cas, de renvoyer vers un autre objet pour la description d'une propriété (cf. § <<_6_11_3>>). Un renvoi vers une valeur ou un élément structuré est impossible puisqu'ils sont dépourvus d'identité.

[#_6_10_4]
==== Les lignes sont des structures spécifiques

L'attribut du tracé de la piste (cf. § <<_6_9_1>>) est défini comme LigneBeotie, laquelle est à son tour définie comme une polyligne (POLYLINE). Une polyligne peut être comprise comme un ensemble de tronçons de lignes (cf. § <<_6_9_2>>). La définition en tant que polyligne n'est en fait qu'une notation abrégée pour un ensemble ordonné de structures, les éléments structurés correspondant à une définition spécifique :

[#listing-06_10-05]
.link:#listing-06_10-05[Listing 06.10-05]
[source]
----
STRUCTURE SegmentBeotie (ABSTRACT) =
  SegmentEndPoint: MANDATORY Beotie.CoordNational;
END SegmentBeotie;

STRUCTURE StartSegmentBeotie EXTENDS SegmentBeotie (FINAL) =
END SegmentBeotie;

STRUCTURE StraightSegmentBeotie EXTENDS SegmentBeotie (FINAL) =
END StraightSegmentBeotie;

STRUCTURE ArcSegmentBeotie EXTENDS SegmentBeotie (FINAL) =
  ArcPoint: MANDATORY Beotie.CoordNational;
  Rayon: Length;
END ArcSegmentBeotie;

CLASS Piste =
  Trace: LIST {2..*} OF SegmentBeotie;
END Piste;
----

[#_6_11]
