[#_6_14]
=== Exceptionnelles Remontées mécaniques de la Dent d'Ili – Règles d'intégrité

[#_6_14_1]
==== Informations de base

Vous vous souvenez que les Remontées mécaniques de la Dent d'Ili souhaitent pouvoir saisir l'état actuel de chacune de leurs lignes et entre autres les conditions météo prévalant à la station supérieure :

[#listing-06_14-01]
.link:#listing-06_14-01[Listing 06.14-01]
[source]
----
CLASS MessageEtat =
  Temperature: MANDATORY –50 .. 50 [oC];
  DirectionVent: (N, NE, E, SE, S, SW, W, NW) CIRCULAR;
  VitesseVent: MANDATORY 0 .. 200 [kmh];
  DelaiAttente: DureeEnMinutes;
  Saisi: MANDATORY InstantHEC;
END MessageEtat;
----

Avec cette définition, un message indiquant qu'un vent souffle d'une direction indéfinie à une vitesse de 60 km/h serait possible. Mais ce n'est pas vraiment le but recherché. Une direction du vent indéfinie doit impliquer le calme plat, c'est à dire un vent de vitesse nulle. Et inversement, dès lors que la vitesse du vent n'est pas nulle, une direction doit lui être attribuée.

[NOTE]
Des situations dans lesquelles un lien préétabli doit exister entre différents attributs d'un objet ou même entre différents objets sont décrites au moyen de *règles d'intégrité*.

Une règle d'intégrité est d'ordinaire décrite au moyen d'une formule dont l'exploitation révèle si la règle est respectée ou non. Le calme plat peut donc être régi par une expression logique du type suivant :

[#listing-06_14-02]
.link:#listing-06_14-02[Listing 06.14-02]
[source]
----
CLASS MessageEtat =
  Temperature: MANDATORY –50 .. 50 [oC];
  DirectionVent: (N, NE, E, SE, S, SW, W, NW) CIRCULAR;
  VitesseVent: MANDATORY 0 .. 200 [kmh];
  DelaiAttente: DureeEnMinutes;
  Saisi: MANDATORY InstantHEC;
  MANDATORY CONSTRAINT
    DEFINED (DirectionVent) == (VitesseVent > 0);
END MessageEtat;
----

Si la direction du vent est définie, alors sa vitesse doit être supérieure à zéro. Si la direction du vent est indéfinie, sa vitesse doit être nulle. Il est par conséquent exigé que l'on mette sur un pied d'égalité (==) le fait que la direction du vent est définie et le fait que la vitesse du vent est supérieure à zéro.

Cependant, les règles d'intégrité peuvent fréquemment être évitées en structurant le modèle différemment. Si l'on intègre les informations relatives au vent au sein d'une structure que l'on définit comme un tout facultatif, plus aucune règle d'intégrité n'est nécessaire. L'élément structuré fait défaut en cas de calme plat et s'il vente, la direction et la vitesse du vent sont nécessaires disponibles.

[#listing-06_14-03]
.link:#listing-06_14-03[Listing 06.14-03]
[source]
----
STRUCTURE InfoVent =
  DirectionVent: MANDATORY (N, NE, E, SE, S, SW, W, NW) CIRCULAR;
  VitesseVent: MANDATORY 0 .. 200 [kmh];
END Vent;

CLASS MessageEtat =
  Temperature: MANDATORY –50 .. 50 [oC];
  Vent: InfoVent;
  DelaiAttente: DureeEnMinutes;
  Saisi: MANDATORY InstantHEC;
END MessageEtat;
----

[WARNING]
La présence de règles d'intégrité – tout particulièrement si elles sont complexes – fait toujours peser un soupçon sur le niveau d'optimisation du modèle. D'un autre côté, il n'y a vraiment aucun intérêt à compliquer artificiellement un modèle simple dans l'unique but d'éviter une règle d'intégrité.

[#_6_14_2]
==== Conditions de plausibilité

Dans l'ensemble, les employés des Remontées mécaniques de la Dent d'Ili gagnent plutôt bien leur vie, sans parler du directeur dont le salaire atteint des sommets.

Les règles d'intégrité s'appliquent généralement à tous les objets de la classe concernée. Dans INTERLIS 2, elles sont désignées par MANDATORY CONSTRAINT. On utilise parfois le terme de règles « dures », parce qu'elles sont toujours à respecter. Mais il existe d'autres règles, à satisfaire dans le cas général mais tolérant des exceptions.

S'agissant d'attributs tels que le salaire mensuel ou la taille d'une personne, le domaine d'admissibilité retenu doit être relativement étendu. Les valeurs de la plupart des objets se concentrent cependant dans un domaine bien plus restreint. Des exceptions sont toutefois possibles, cas par exemple du salaire du directeur.

[#listing-06_14-04]
.link:#listing-06_14-04[Listing 06.14-04]
[source]
----
ASSOCIATION Salariat =
  ...
  SalaireMensuel: MANDATORY 0 .. 20000 [Couronnes];
  ...
  CONSTRAINT >= 95%
    SalaireMensuel < 10000;
END Salariat;
----

On estime que le salaire mensuel est inférieur à 10'000 couronnes dans au moins (>=) 95% des cas. Si un modèle intègre de telles conditions « souples », la plausibilité des données entrées peut être vérifiée et un contrôle statistique effectué.

[#_6_14_3]
==== Conditions d'unicité

Comment les salariés ou les actionnaires des entreprises de transport en montagne sont-ils identifiés ? Il serait très tentant mais inapproprié d'utiliser le nom et le prénom à cet effet :

[#listing-06_14-05]
.link:#listing-06_14-05[Listing 06.14-05]
[source]
----
CLASS Personne =
  Nom: TEXT*50;
  Prenom: TEXT*20;
  UNIQUE Nom, Prenom;
END Personne;
----

Il ne serait donc pas permis d'enregistrer deux personnes différentes possédant le même nom et le même prénom. Ainsi, le nouveau conducteur de locomotive Jean Martin ne pourrait être embauché qu'une fois son homonyme de la comptabilité limogé.

Quelle condition d'unicité pourrait être plus appropriée ? Et d'abord, pourquoi utiliser des conditions d'unicité ?

[NOTE]
Une *condition d'unicité* ne sert pas à l'identification d'un objet au sein d'un logiciel donné mais décrit les combinaisons d'attributs devant concrètement être uniques.

[NOTE]
Au sein d'un logiciel comme durant un transfert de données, un objet est repéré par une *identification d'objet* technique, dénuée de toute signification pour l'application.

Une condition d'unicité n'est par conséquent pas requise pour chaque classe d'objet dans le seul but de pouvoir identifier un objet. Il suffit que l'objet de données correspondant à la personne effective puisse être trouvé lors de son enregistrement. Il peut également être fait appel à des attributs, des relations, etc. dans ce cadre sans qu'une combinaison ait à être unique.

Si l'on souhaite toutefois introduire une identification externe au système, compréhensible par tout un chacun par exemple, il est alors nécessaire de disposer d'un attribut ou d'une combinaison d'attributs dont les valeurs sont uniques sur l'ensemble des objets considérés. Des attributs artificiels sont souvent créés à cette fin (numéro d'assurance, de client, d'article, etc.)

[WARNING]
Les identificateurs artificiels sont autant que possible à éviter. Lorsqu'ils sont inévitables, il convient de veiller à ce que les informations qu'ils contiennent ne fassent pas double emploi avec celles d'autres attributs.

Ce problème a été résolu d'une manière très simple pour les Remontées mécaniques de la Dent d'Ili, en introduisant tout bêtement un numéro personnel. Dès qu'une personne rejoint les Remontées mécaniques de la Dent d'Ili, un numéro non encore attribué lui est affecté.

[#listing-06_14-06]
.link:#listing-06_14-06[Listing 06.14-06]
[source]
----
CLASS Personne =
  Nom: TEXT*50;
  Prenom: TEXT*20;
  NumeroPersonnel: 1 .. 9999;
  UNIQUE NumeroPersonnel;
END Personne;
----

Les choses deviendraient plus délicates si la classe par laquelle les personnes sont décrites était définie non pas par les Remontées mécaniques de la Dent d'Ili mais par l'Association nationale. Les numéros affectés à toutes les personnes dans le cadre de l'Association devraient alors être uniques – même en cas de saisie décentralisée. L'existence de deux numéros identiques (par exemple un pour les Remontées mécaniques de la Dent d'Ili et l'autre pour les Remontées mécaniques des montagnes bleues) signifierait la violation de la condition.

[NOTE]
Les conditions d'unicité valent toujours pour tous les objets de la classe à laquelle la condition s'applique – même en cas de correspondance indirecte (sous la forme d'une extension de la classe).

Une société de remontées mécaniques peut porter plusieurs noms, mais il ne doit exister qu'une seule désignation dans chaque langue : les Remontées mécaniques de la Dent d'Ili ne peuvent donc porter aucun autre nom en français. Cette restriction ne s'applique toutefois que localement, donc à une entreprise donnée. Les Remontées mécaniques des montagnes bleues possèdent elles aussi un nom en français. Autrement dit, il existe plus d'un nom dans une langue donnée si l'on considère l'ensemble des entreprises de transport. Et par conséquent, l'unicité de la désignation dans une langue donnée ne s'applique qu'à l'entreprise considérée.

[NOTE]
Si un objet comporte des sous-structures, l'unicité ne doit généralement pas s'appliquer « globalement » aux éléments de l'ensemble des sous-structures, au contraire du cas des objets effectifs. Elle ne se rapporte d'ordinaire que « localement » aux éléments de sous-structure d'un seul objet.

[#listing-06_14-07]
.link:#listing-06_14-07[Listing 06.14-07]
[source]
----
STRUCTURE Designation =
  Nom: TEXT*100;
  Langue: TEXT*2;
END Designation;

STRUCTURE DesignationEntreprise EXTENDS Designation =
  NomAbrege: TEXT*10;
END DesignationEntreprise;

CLASS SocieteRemonteesMecaniques =
  Noms: BAG {1..*} OF DesignationEntreprise;
  UNIQUE
    (LOCAL) Noms : Langue;
END SocieteRemonteesMecaniques;
----

Comment alors parvenir à éviter tout conflit entre les noms abrégés des différentes entreprises ? Les Remontées mécaniques des montagnes bleues tout comme les Remontées mécaniques des montagnes blanches revendiquent le nom abrégé RMB. Dans INTERLIS 2, il est possible de formuler des règles d'intégrité valant non seulement pour les classes d'objets ou des éléments structurés locaux, mais également pour des vues (cf. § <<_6_17>>). Une vue donnée permet de faire d'éléments structurés des objets quasi indépendants, pour lesquels une nouvelle condition d'unicité peut à son tour être formulée.

[#_6_14_4]
==== Condition d'existence

Au contraire d'un chemin de fer à crémaillère ou d'un funiculaire, le tracé d'un téléphérique, d'une télécabine, d'un remonte-pente, etc. est lié à des éléments fixes : les stations inférieure et supérieure de même que les pylônes intermédiaires.

Ce lien doit pouvoir être exprimé. Les lignes d'INTERLIS 2 relient toutefois des points d'appui qui sont avant tout des coordonnées et n'entretiennent aucun rapport avec des objets du modèle tels que les pylônes. Le lien entre le tracé et d'autres objets peut cependant être formulé sous la forme de règles d'intégrité.

Avec la définition suivante, chaque point du tracé doit s'appuyer sur la position d'un pylône (Pylone:Position), de la station inférieure d'une remontée mécanique (RemonteeMecanique:PosStationInf) ou (OR) de la station supérieure d'une remontée mécanique (RemonteeMecanique:PosStationSup).

[#listing-06_14-08]
.link:#listing-06_14-08[Listing 06.14-08]
[source]
----
CLASS RemonteeDependanteTerrain EXTENDS RemonteeMecanique =
  EXISTENCE CONSTRAINT
    Trace REQUIRED IN
      Pylone:Position
      OR
      RemonteeMecanique:PosStationInf
      OR
      RemonteeMecanique:PosStationSup;
END RemonteeDependanteTerrain;
----

De telles conditions d'existence ne peuvent pas uniquement être formulées en lien avec des remontées mais peuvent également l'être avec des attributs ordinaires. Sur le plan conceptuel, elles peuvent toujours être considérées comme une forme de relation faible.

[#_6_14_5]
==== Héritage de règles d'intégrité

Une règle d'intégrité a déjà été formulée pour la remontée mécanique elle-même : le tracé doit débuter à la station inférieure pour s'achever à la station supérieure. Autrement dit, le premier point du tracé (Tracee -> Segments[FIRST] -> SegmentEndPoint) doit correspondre à la position de la station inférieure et (AND) le dernier point du tracé (Tracee -> Segments[LAST] -> SegmentEndPoint) doit coïncider avec la position de la station supérieure.

Le paragraphe <<_7_3>> expose la manière dont les lignes sont construites et présente l'attribut SegmentEndPoint, symbolisant le point final d'un segment de ligne.

[#listing-06_14-09]
.link:#listing-06_14-09[Listing 06.14-09]
[source]
----
CLASS RemonteeMecanique =
  PosStationInf: Beotie.CoordNational3;
  PosStationSup: Beotie.CoordNational3;
  Trace: LigneBeotieNormale;
  MANDATORY CONSTRAINT
    Tracee -> Segments[FIRST] -> SegmentEndPoint == PARENT == PosStationInf
    AND
    Tracee -> Segments[LAST] -> SegmentEndPoint == PARENT == PosStationSup;
END RemonteeMecanique;
----

Que signifie une telle définition pour d'éventuelles extensions de cette classe ?

[NOTE]
Des extensions de classes ne peuvent pas faire perdre leur validité à des règles d'intégrité. Elles ne peuvent que définir des règles supplémentaires.

[#_6_15]
