[#_7_2]
=== Le cours de l'euro fluctue quotidiennement – Paramètres et fonctions

Le prix est indiqué dans la monnaie nationale pour chacun des types de billets.  Mais il doit également être communiqué en euros et en dollars dans l'intérêt des touristes étrangers. Il ne faudrait toutefois pas que les prix de l'ensemble des types de billets aient à être saisis une nouvelle fois à la moindre fluctuation des taux de change. Ils devraient donc pouvoir se déduire du prix dans la monnaie nationale.

[#listing-07_02-01]
.link:#listing-07_02-01[Listing 07.02-01]
[source]
----
CLASS TypeBillet =
  Nom: Text * 100;
  Prix_COURONNE: 0.00 .. 5000.00 [Beotie.Couronne];
  Prix_EUR: 0 .. 4000 [EUR] := COURONNEenEUR (Prix_COURONNE);
  Prix_USD: 0 .. 4000 [USD] := COURONNEenUSD (Prix_COURONNE);
END TypeBillet;
----

Lorsque les données du système sont à présenter ou à mettre à disposition de WebSys, les prix en euros ou en dollars sont recalculés à partir des prix en monnaie nationale. Le calcul s'effectue au moyen des deux fonctions COURONNEenEUR et COURONNEenUSD. Mais comment LiftSys en particulier et tout système en général peut-il avoir connaissance de l'objet de cette fonction ?

L'information la plus importante au plan conceptuel réside dans le fait que les deux prix en monnaie étrangère ne sont pas traités comme des données indépendantes mais comme une résultante du prix en couronnes. Il suffit par conséquent, pour une fonction donnée, de définir son nom et ses paramètres.

[#listing-07_02-02]
.link:#listing-07_02-02[Listing 07.02-02]
[source]
----
FUNCTION COURONNEenEUR (Couronne: NUMERIC [Beotie.Couronne]): NUMERIC [EUR]
  // Conversion en euros //;
----

L'objectif effectivement assigné à la fonction n'est indiqué que sous forme d'explication entre signes « // ». Son implémentation reste l'affaire des systèmes. De telles définitions sont à limiter à un nombre restreint de modèles de base car elles doivent faire l'objet d'accords passés avec les producteurs de systèmes. Dans INTERLIS 2, l'existence d'un tel accord est signalé par un contrat. Les fonctions ne peuvent être définies que dans des modèles pour lesquels un contrat a été conclu.

[#listing-07_02-03]
.link:#listing-07_02-03[Listing 07.02-03]
[source]
----
CONTRACTED MODEL IlisTour AT http://www.interlis.ch/models/beotie
  VERSION "2008-01" =
  ...
END IlisTour;
----

Les fonctions sont à formuler de la manière la plus générale possible si l'on souhaite que leur nombre reste limité. Pour prendre un exemple, la fonction COURONNEenEUR aurait pu être remplacée par une fonction de division utilisable en toutes circonstances.

[#listing-07_02-04]
.link:#listing-07_02-04[Listing 07.02-04]
[source]
----
FUNCTION Division (Dividende: NUMERIC, Diviseur: NUMERIC): NUMERIC;
----

Il faudrait cependant s'octroyer quelques possibilités de contrôle supplémentaires car on ne dispose d'aucune assurance que la première valeur est un montant exprimé dans la monnaie nationale. La formulation suivante le garantit en revanche.

[#listing-07_02-05]
.link:#listing-07_02-05[Listing 07.02-05]
[source]
----
FUNCTION EnMonnaie (Couronne: NUMERIC [Beotie.Couronne],
                    TauxChange: NUMERIC [Beotie.Couronne]):
  NUMERIC [MONEY];
----

Mais d'où provient le taux de change ? On pourrait envisager que certaines valeurs telles que le cours de l'euro ou du dollar soient disponibles dans les systèmes sous forme de paramètres. Mais comme cela impliquerait à nouveau de s'immiscer dans les systèmes, la définition de paramètres systèmes ne serait autorisée que dans le cadre de contrats.

[#listing-07_02-06]
.link:#listing-07_02-06[Listing 07.02-06]
[source]
----
PARAMETER
  Cours_EUR: 0.000 .. 5.000 [Beotie.Couronne]; !! Valeur d'un euro
                                               !! en couronnes
  Cours_USD: 0.000 .. 5.000 [Beotie.Couronne];

CLASS TypeBillet =
  Nom: Text * 100;
  Prix_COURONNE: 0.00 .. 5000.00 [Beotie.Couronne];
  Prix_EUR: 0 .. 4000 [EUR] := EnMonnaie (Prix_COURONNE, PARAMETER Cours_EUR);
  Prix_USD: 0 .. 4000 [USD] := EnMonnaie (Prix_COURONNE, PARAMETER Cours_USD);
END TypeBillet;
----

[#_7_3]
