[#_8_5]
=== Le tire-fesses du « Tal der gelben Murmeltiere » – Langues étrangères et transfert de données

Le « Tal der gelben Murmeltiere » se trouve sur le versant opposé de l'Aiguille Noire. En dehors du fait que l'on y parle allemand et que les marmottes de cette vallée possèdent une fourrure aux tons dorés, la différence par rapport au Val d'Ili n'est pas criante.

En plus, un tire-fesses y réjouit le coeur des enfants. Comment la durée de son trajet est-elle transmise à l'Association nationale des offices de tourisme puisque les désignations utilisées dans le cadre du modèle se reflètent aussi dans la constitution du fichier de transfert ? Ainsi, les données du Val d'Ili comportent des lignes telles que ++<++LapsTemps++>++3++<++/LapsTemps++>++. Si l'on traduit le modèle de données dans une autre langue, le format de transfert correspondant subit lui aussi des modifications.

Comment l'Association nationale des offices de tourisme gère-t-elle alors le fait que le fichier de transfert d'une vallée contient la ligne ++<++LapsTemps++>++3++<++/LapsTemps++>++ et que celui de la vallée voisine contient la ligne ++<++Dauer++>++3++<++/Dauer++>++?

L'Association n'a pas besoin de faire l'acquisition d'un logiciel séparé pour chacune des langues nationales. INTERLIS veille à ce que le transfert se passe sans accroc, en dépit de son caractère multilingue. La seule condition à respecter est que la structure du modèle de données ne subisse aucune modification lors de la traduction. Comme évoqué au paragraphe <<_6_18>>, un outil (le compilateur INTERLIS) est à la disposition des utilisateurs pour vérifier si la structure d'un modèle de données traduit présente une structure identique à celle de l'original.

