[#_8_2]
=== Des signes cabalistiques à profusion – Règles de transfert sur la base de XML

Mais que contenait ce fichier ? Pour le savoir, on l'ouvrit dans un éditeur de texte normal :

.Le tire-fesses du Val d'Ili, extrait du transfert intégral des données du Val d'Ili. La norme INTERLIS fixe le degré de spécification d'un tel fichier de transfert pour un modèle de données bien défini.
[#listing-08_02-01]
.link:#listing-08_02-01[Listing 08.02-01]
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
...
<BASKET BID="xBOTOURDI01234567" TOPICS="IlisTour.RemonteesMecaniques">
  <IlisTour.Remontees_RDI.Remontee_RDI TID="xBOTOURDI04231336">
    <Noms>
      <NatTour.Designation>
        <Nom>Tire-fesses Ili-village</Nom> <1>
        <Langue>fr</Langue>
      </NatTour.Designation>
    </Noms>
    ...
    <PosStationSup>
      <P>
        <C1>8020.60</C1>
        <C2>13188.62</C2>
        <C3>1789.04</C3>
      </P>
    </PosStationSup>
    <DureeTrajet>
      <Beotie.DureeEnMinutes>
        <LapsTemps>3</LapsTemps>
      </Beotie.DureeEnMinutes>
    </DureeTrajet>
    <Genre>Remonte_pente</Genre>
    ...
    <ImageStationSuperieure>
      http://www.ilishornbahnen.com/webcam?bahn=pony4
    </ImageStationSuperieure>
    ...
  </IlisTour.Remontees_RDI.Remontee_RDI>
</BASKET>
...
----

Beaucoup de signes « inférieur à » et « supérieur à », une référence à XML tout au début (on en a déjà entendu parler de ça !), entourée de points d'interrogation... Ah, enfin quelque chose d'un peu plus simple :

<1> le tire-fesses d'Ili-village.

La structure du fichier de transfert est différente selon le modèle de données mais elle n'est évidemment pas quelconque : la norme INTERLIS contient des règles précises, prescrivant la manière dont le format XML associé se déduit d'un modèle de données.

Soit, tout cela est un peu compliqué – mais il a tout de même été possible d'utiliser LiftSys sans même avoir à saisir manuellement tous ces signes cabalistiques. Et sans même recourir à un logiciel particulier, on a pu se rendre compte que la durée du trajet avec le tire-fesses était de 3 minutes.

Selon l'informaticien, il devrait encore être possible, dans 40 ans, d'utiliser ces données, même si les fournisseurs des programmes initiaux font faillite entre temps, que quinze nouvelles versions du programme se sont succédé dans l'intervalle ou que les ordinateurs changent radicalement d'aspect d'ici là. Cette affirmation semblait crédible, preuve en était bien que sans la moindre documentation, en se contentant de lire la version papier présentée, les données étaient compréhensibles (non sans mal tout de même).

Mais que signifie donc ce texte étrange, « TID="xBOTOURDI04231336" »? Il désigne tout simplement le tire-fesses au sein du fichier de transfert. La valeur ne joue un rôle que dans le cadre du transfert : cette identification d'objet est présente partout où il est fait référence au tire-fesses dans le fichier de transfert. Il a été indiqué, lors de l'installation de LiftSys, que toutes les identifications devaient débuter par xBOTOURDI, comme l'Association nationale des offices de tourisme l'avait demandé dans son courrier.

Les identifications d'objets débutent par un code de pays conforme à la norme ISO 3166 (ch pour la Suisse, fr pour la France, etc.) et comprennent six caractères supplémentaires, attribués par un service central habilité à les délivrer. Les huit autres caractères sont automatiquement attribués par le système informatique.

L'annexe D du manuel de référence d'INTERLIS explique en détail l'attribution des identifications d'objets.

[#_8_3]
