[#_9_1]
=== Tous les chemins mènent à la Dent d'Ili – Il n'existe pas de modèle parfait

Les Ilinois savent bien que leur modèle de données peut prêter le flanc à la critique. Le Val d'Ili étant par ailleurs purement imaginaire et ne servant qu'aux besoins de la cause, il n'a pas paru opportun de scruter tous les aspects du modèle de données pour en déceler les failles. L'objectif était avant tout de présenter les différentes facettes de la modélisation et les instruments développés à cette fin.

Il n'en reste pas moins qu'aucun modèle ne peut échapper à la question de sa justesse, ou pour être plus précis, de sa pertinence.

Il est assurément très insuffisant d'estimer qu'un modèle est correct ou exact pour la simple raison qu'il satisfait aux exigences purement formelles du language de description utilisé. L'acceptation d'un modèle par le compilateur INTERLIS ne préjuge en rien de la pertinence de son contenu.

Le proverbe selon lequel « tous les chemins mènent à Rome » – ou dans le cas d'espèce, à la Dent d'Ili – reflète bien plus fidèlement la situation. Il existe manifestement de nombreuses possibilités pour modéliser un état de fait donné, ce qui ne signifie pas pour autant que tous les modèles envisageables soient de qualité égale. Toutes sortes de chemins mènent à la Dent d'Ili, certains sont larges et carrossables, d'autres étroits et cahoteux, il existe même des sentiers abrupts d'où la vue est exceptionnelle tout du long ! Et l'on ne choisit pas tous les jours le même chemin pour parvenir à sa destination. Enfin, les besoins et par suite les critères d'appréciation ne sont pas toujours identiques, eux non plus.

C'est pourquoi différents critères d'appréciation d'une certaine importance pour la modélisation de données vont faire l'objet des paragraphes suivants.

[#_9_2]
