[#_9_2]
=== La Dent d'Ili considérée depuis des points de vue différents – Données originales et vues

Si, dans le cadre d'une modélisation de données, on se laisse guider par des besoins immédiats, il existe un risque réel que les données soient saisies d'une manière inadéquate. Il n'est par exemple pas judicieux d'envisager l'âge comme un attribut pour une personne puisqu'il change constamment. Mieux vaut définir la date de naissance comme attribut et dériver l'âge à partir de celle-ci et de la date actuelle (cf. § <<_6_17_2>>), au moyen d'une vue.

Lorsque le modèle de données est constitué de telle façon qu'il corresponde à la réalité et non à une certaine vision des choses, il nous est possible de réagir avec souplesse pour les utilisations concrètes, en les dérivant des données originales. Les données contiennent alors la Dent d'Ili et non la vue que l'on en a depuis Ili-village ou Ili-les-Bains. Ces perspectives comme bien d'autres peuvent être déduites des données originales sous forme de vues.

La dérivation des vues requises à partir de données modélisées de manière « idéale » peut parfois se montrer extrêmement exigeante. Les vues comprenant des lois de formation intégrant des calculs géométriques ne sont en particulier pas toujours aisées à mettre en œuvre. La décision de s'écarter du droit chemin pour orienter le modèle de données vers les vues est souvent difficile à prendre et dépend en règle générale de critères d'appréciation supplémentaires. Même si l'on opte pour un modèle ne décrivant pas les données effectives mais une vue de celles-ci, il reste judicieux de s'interroger sur ce que serait le « bon » modèle. Il est alors plus facile d'en revenir à ce modèle le moment voulu et de surmonter les inconvénients inhérents au modèle orienté vers les vues.

Le principal inconvénient d'un modèle orienté vers les vues se fait jour à l'occasion de la saisie et plus encore de la mise à jour des données. Si, pour chaque entrée d'immeuble, on gère par exemple le nom de la rue, le numéro du bâtiment, le numéro postal d'acheminement et la localité comme des attributs, le risque de voir des erreurs telles que des orthographes différentes se glisser dans ces données est bien réel. Par ailleurs, le volume de travail requis par la saisie est notablement plus élevé. Et la situation ne fait qu'empirer au niveau de la mise à jour si le nouveau lotissement d'Ili-moulin est par exemple transformé en localité (dotée de son propre numéro postal d'acheminement) à laquelle les dernières maisons d'Ili-village sont rattachées. Que faire : procéder à la mutation de toutes les entrées d'immeubles concernées ? Il serait plus judicieux d'introduire la nouvelle localité avec les limites géographiques qui lui sont associées et d'adapter celles d'Ili-village en conséquence.

Un modèle vraiment pertinent se distingue par le fait qu'un changement de situation dans la réalité ne conduit qu'à une seule modification dans les données. Le reste se déduit de vues.

[#_9_3]
