[#_10]
== Rapport final pour les administrations et le management

Le bon fonctionnement de la nouvelle solution mise en place dans le Val d'Ili a bien entendu été fêté comme il se doit. La syndic de la commune était toutefois désireuse d'en savoir un peu plus sur l'aspect technique de cette réalisation. Quelles ont été les clefs du succès ? Pourquoi a-t-il été possible de mener cette tâche à bien tout en conservant les systèmes existants ? Pourquoi évalue-t-on le risque d'être contraint à une révision importante en cas de remplacement de l'un des systèmes impliqués à un niveau aussi faible ? C'est pour trouver des réponses à ces questions et préparer sereinement la courte allocution qu'elle devait prononcer qu'elle s'est plongée dans la lecture du bref rapport rédigé par le secrétaire des constructions et le responsable technique des Remontées mécaniques de la Dent d'Ili.

++*++ ++*++ ++*++ ++*++ ++*++


include::10_01.adoc[]

include::10_02.adoc[]

include::10_03.adoc[]

include::10_04.adoc[]

include::10_05.adoc[]

include::10_06.adoc[]
