[#_10_4]
=== IV. Transfert de données indépendant de tout système

Ce qui vaut pour la description de la structure des données vaut également pour les données elles-mêmes. Il ne faut donc pas uniquement normaliser la description de données, mais également leur transfert. Durant la transmission des données d'un système vers un autre, la communication s'effectue pour ainsi dire en esperanto tandis que la langue maternelle concernée reste en usage au sein de chacun des systèmes.

Après une réflexion aussi approfondie que celle menée en vue de la structuration des données, on souhaiterait vivement ne plus à avoir à se préoccuper de détails de cet ordre. A nouveau, le recours à INTERLIS s'est pleinement justifié ici : la description de la structure de données définit en même temps la manière dont les données associées sont transférées. 

Le point le plus important dans ce contexte est que la description de données ne puisse pas uniquement être lue et comprise par des êtres humains, mais que des logiciels informatiques parviennent également à la décrypter, grâce à la définition formalisée du langage. La description de données et les règles de transfert établissent alors clairement la manière dont le transfert de données consécutif doit être organisé.

[#_10_5]
