[#_10_3]
=== III. Description de la structure des données indépendante de tout système

Pour qu'une représentation numérique de la réalité – des données en d'autres termes – puisse être transférée d'un système vers un autre, il est impératif que la structure et la présentation des données soient définies avec une parfaite clarté. Cerise sur le gâteau : ces descriptions de structure doivent elles aussi être indépendantes de tout système concret. Elles doivent être réalisées de telle façon à être comprises et interprétées à l'identique par les spécialistes en charge des applications et les services techniques de tous les intervenants impliqués dans le processus. Dans le cas idéal, la description est même conçue de manière à n'être pas uniquement comprise par des êtres humains mais également par des machines ou plus exactement par des programmes informatiques. Une sorte d'esperanto formalisé propre à la description de données est requis à cet effet.

L'esperanto n'est jamais parvenu à s'imposer comme langue véhiculaire. D'autres, plus vivantes ou moins ardues et artificielles lui ont ravi la place. Les choses sont un peu différentes dans le domaine technique : quiconque ne cherche pas à s'affranchir des systèmes finit par s'en rendre dépendant. Et ceux-ci ont une durée de vie relativement limitée. D'où la conclusion qu'un esperanto, compris au sens de norme indépendante de tout système, est nécessaire en dépit de nombreuses normes de fait largement établies. Un langage graphique, le langage de modélisation unifié (_Unified Modeling Language, UML_), s'est assez largement diffusé au plan mondial dans le domaine de la modélisation de données.

D'intenses discussions ont préludé à l'élaboration d'un modèle de la réalité. La première tâche a consisté à définir clairement les objets les plus importants, la manière de les désigner pour être compris de tous, les relations qu'ils entretenaient les uns avec les autres et les propriétés supplémentaires qu'ils possédaient. Le procès-verbal de ces discussions était toujours tenu dans le langage visuel UML et les complétait par des explications et des commentaires. Comme il s'est avéré que les images étaient surchargées de détails et qu'elles ne présentaient parfois plus la précision suffisante, un moyen de description supplémentaire a été introduit : INTERLIS. Les structures de données peuvent être décrites par ce moyen, de façon analogue à ce que permet un langage de programmation.

Une propriété importante d'UML et d'INTERLIS 2 réside dans le fait que ces langages acceptent l'utilisation de descriptions de données provenant de tiers. Il a ainsi été possible de tirer avantage de définitions effectuées par la mensuration officielle, dans le domaine par exemple des adresses de bâtiments. La description de données de l'Association nationale des offices de tourisme a non seulement été utilisée mais a également été complétée pour l'adapter aux besoins locaux.

[#_10_4]
