[#_10_5]
=== V. Répercussions différentes sur les systèmes impliqués

Plusieurs systèmes informatiques ont été mis en oeuvre dans le cadre de la solution globale et le recours aux systèmes utilisés jusqu'alors a par ailleurs pu se poursuivre. Ni UML ni INTERLIS ne prescrivent la manière dont les systèmes doivent être structurés, ils se contentent de régir la manière dont les données sont à livrer afin qu'elles se conforment à la représentation conceptuelle élaborée.

Le système du service des constructions était directement en mesure de générer les données à transférer et de lire les données reçues. Un convertisseur a été mis en place sur le système des Remontées mécaniques de la Dent d'Ili, il s'agit d'un logiciel transformant les données spécifiques au système en un format de transfert neutre. En ce qui concerne les systèmes plus modestes utilisés pour la saisie aux stations inférieures, des programmes très simples ont permis de garantir la transmission d'un jeu de données toujours correct à la centrale sous forme d'une livraison incrémentielle assise sur la mesure réalisée.

Qu'en est-il enfin du système de l'Association nationale ? Des fichiers intégrant les compléments définis par nos soins ont pu lui être transmis et, grâce au principe de la lecture polymorphe, ils ne lui ont posé aucun problème.

Le fait qu'INTERLIS 2 se fonde sur le langage XML (_Extensible Markup Language_) n'est du reste pas étranger à la réussite de toute l'entreprise.

[#_10_6]
