[#_10_2]
=== II. Les choses, leur représentation et l'usure du temps

L'appel à un spécialiste supplémentaire a porté ses fruits, en dépit de discussions initiales un peu surprenantes, dirons-nous. Le vocabulaire technique était absent ou très vite balayé cédant la place à une réflexion approfondie sur les choses à modéliser.

Première conclusion : les choses ne sont pas enfouies dans les entrailles d'un ordinateur pas plus qu'il ne s'agit de ce qu'il est capable de recracher sous forme d'images, de tableaux voire de présentations. Les choses existent dans le monde réel et y interagissent.

Ce que l'ordinateur contient, on peut le comparer à une maquette en bois ou à un moulage en plâtre. Les photos que l'on en fait sous des angles ou des éclairages différents peuvent être comparées à ce que l'on voit sur l'écran de l'ordinateur ou sur des sorties papier. Maquette en bois ou moulage en plâtre, une chose est sûre en tout cas : la reproduction initiale de la réalité est un travail de titan. Bien du temps et des efforts sont nécessaires  jusqu'à ce que tous les immeubles, toutes les routes et toutes les remontées mécaniques existant dans la réalité soient intégrés de manière simplifiée dans la représentation ! Et il y a pire que la saisie initiale : la mise à jour des données. Des modifications deviennent indispensables au bout de très peu de temps pour que la représentation conserve toute son actualité. Sans compter que le temps fait son oeuvre, érodant les structures en plâtre si friables… Autant dire que l'on est logé à meilleure enseigne avec l'informatique ! Des compléments sont bien entendu nécessaires lorsque la réalité change, mais le reste des informations conserve toute son actualité.

Vraiment ? Non, même si la vitesse n'est pas aussi effrayante que dans le cas du moulage en plâtre. Mais au bout de quelques années à peine, le besoin d'un nouvel ordinateur plus performant se fait sentir et peu de temps après, le logiciel de traitement montre ses premiers signes de fatigue. Le moment est alors venu de passer à de nouveaux programmes. Comment alors transférer la représentation numérique de la réalité de l'ancien système vers le nouveau ? Comment pour ainsi dire faire entrer le moulage existant dans son nouveau moule sans lui faire subir de dégâts et être contraint à un remodelage complet ?

[#_10_3]
