[#_11]
== Index

Les renvois à l'exemple détaillé du <<_4>> sont indiqués en _italique_.

A

Abstrait _37_, 48

Accents 25

Adresse 31, 123

Internet _cf._ URI

Agrégation 101

cas des relations _37_, 83

de vues 101

Aire (area) _cf._ Partition du territoire

Altitude 65

Altitude ellipsoïdique 65

Altitude orthométrique 65

Angle 67

Appui sur l'existant 17

Arc de cercle 69, 108

Association _37_, 83

Attribut 14

cas des relations 84

facultatif 60

obligatoire 60

B

Booch 29

C

Cardinalité 13

Cas général _cf._ Héritage

Cas particulier _cf._ Héritage

Catalogue d'objets 11

Chaîne de caractères _36_

Chaînes de caractères 59

Champ 14

Classe de base _cf._ Héritage

Classe d'objets 12

Clothoïde 107

Codage 25

Codage de caractères 25

Colonne 14

Compatibilité 50

Compilateur 32, 103, 115

Composition _41_, 83

Condition d'existence 94

Connection _cf._ Relation

Conteneur 95, 114

Contrat 106

Coordonnées _34_, _37_, 61

pour l'établissement de relations 89

spatiales _35_, 65

Courbe de Bézier 107

D

Description _cf_ Modèle de données

Description de données 29

Diagramme de classe 12

Direction 67

Domaine de valeurs 14, _34_, 61

géométrique 68

numérique _38_, 54

structuré 80

Durabilité 112

Durée _35_, _37_, 78

E

Echange de données _cf._ Transfert

Ellipsoïde 62

Empreinte 12

Enclave 71

Ensemble d'entités 12

Enumération _37_, 56

achevée 58

cyclique _42_, 58

et héritage _39_, 56

ordonnée _42_, 58

structuré 59

Exemplaire 12

Extension _cf._ Héritage

F

Fédéralisme 30, 50, 123

Fonction _39_, 106

G

Genres _37_, 56

Géoïde 65

GML 32

Graphique 27

H

Héritage

à grande échelle 21, 50

de domaines de valeurs numériques 54

de règles d'intégrité 94

de relations 87

de structures 74

de thèmes 21, 50

de vues 102

d'énumérations _39_, 58

détaillé à l'excès 46

multiple 51

principes 45

Hériter _cf._ Héritage

I

Identification

affectation 113

lors du transfert 113, 114, 115

par des attributs 92

Identification d'objet _cf._ Identification

Indéfini 60

Indépendance vis-à-vis de tout système 105

Indicateur _cf._ Relation

Inspection 101

Instant _35_, 81

Integer 53

ISO 19100 31

ISO 3166 113

J

Jeu de caractères 25

Jeu de données 12

Jonction 99

L

Lecture polymorphe 25, 114, 123

Ligne 68

dans l'espace 72

formée spécifique 107

orientée 70

structuration 69, 75, 107

Livraison complémentaire 17

Livraison incrémentielle 17

Loi de formation _cf._ Vue

M

Mensuration 31, 123

Mensuration officielle 31, 123

Métadonnées 63

Méthode fondée sur un modèle 32

Mise à jour 122

Modèle _cf._ Modèle de données

Modèle de données 12, 121

multilingue 103

représentation 29

standardisé 31, 97

Module 18

Monnaie 54, 106

Multilinguisme 75

cas de propriétés d'objets _36_

cas de transfert 115

de modèles de données 103

O

Object Management Group 32

Objet 12

Objet proxy 114

OMG 32

OMT 29

OOSE 29

Ordre de grandeur 53

P

Package 18

Paquet 18

Paramètre 106

Partition du territoire _42_, 71

Plausibilité 91

Point auxiliaire 108

Polymorphisme 49

lors du transfert 25, 114, 123

Précision

de lignes 69, 108

de valeurs numériques 54

Projection

de coordonnées 62

de vues 98

Propriété 14

abstraite 55

hériter _cf._ Héritage

R

Rayon 108

Recouvrement

de lignes 69

de surface _cf._ Partition du territoire

Réel (valeur en virgule flottante) 53

Règle d'intégrité _40_, 90

et héritage 94

pour des points d'appui 94

Relation 12, _37_, 82

agrégation 83

association 83

classe relationnelle _38_

composition _41_, 83

dérivable _40_, 89

et héritage 87

intensité 83, 88

'inter-thèmes' 96

multiple _38_, 84

ordonnée 85

Renvoi _cf._ Relation

Réplique 114

Réseaux de conduites 31

Restriction _cf._ Héritage

Rôle _37_, 82

S

Schéma _cf._ Modèle de données

Segment 69

Segment de droite 69, 107

Sous-classe _cf._ Héritage

Sous-énumération 59

Spline 107

Structure 74

d' agrégation 101

d' inspection 101

et héritage 74

Substitut 114

Super-classe _cf._ Héritage

Sur-classe _cf._ Héritage

Surface 70

Système de coordonnées 62

Système de référence

de coordonnées 68

d'instants 81

T

Table 12

Texte _36_, 59

Thème 20, 95

Topic _cf._ Thème

Transfert 17, 111

à base de modèle 23, 123

avec un logiciel de conversion 25, 105

de lignes 108

des données de l'exemple _43_

et multilinguisme 115

format 23

identification 113

incrémentiel 113, 115

indépendant d'un système 123

intégral 17, 115

lecture polymorphe 114

spécifique au système 24

vers l'amont 25

Type _cf._ Type de données

Type d'attribut _cf._ Type de données

Type de données 14, _34_, 61

géométrique 68

numérique _38_, 54

structuré 80

U

Unicité _36_, 91, 115

Unified Modeling Language 29, 122

éditeur UML 32

Union 100

Unité _34_, 54

Uplet 12

URI _40_, 59

V

Valeur en virgule flottante 53

View _cf._ Vue

Vue 26, _40_, 97

agrégation 101

constitution pas à pas 101

et héritage 102

inspection 101

jonction 99

loi de formation 98

union 100

X

XML 32, 111, 123
